### ISSUE TITLE
think about command access in a long document or in mobile

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#10]
popover-style, or sticking to bottom?

maybe move it to the top, since it keeps jumping around. Pin it to the t    op, esp. for mobile use?

**Comment by gauravano** [comment]
Command access?  

![command_access](https://user-images.githubusercontent.com/20878070/50571761-96772b00-0dd8-11e9-806c-511b4db32431.png)

**Comment by rexagod** [comment]
Isn't this similar to #124?

**Comment by jywarren** [comment]
i think it is

**Comment by gauravano** [comment]
Closing this one then. Thanks @rexagod for linking.
