### ISSUE TITLE
Tests don't run in Node v4, but work in Node v5+

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#111]
As of PublicLab.Editor `v3.x`, tests don't run without error in Node v4, though they work in higher versions of Node.

https://github.com/publiclab/PublicLab.Editor/pull/110 documents this, in the second-to-last tests. Node v5, 6, and 7 run fine, but Node v4 and v4.2 do not. We ended up deprecating Node v4 for tests, but would like to re-open it because v4.2 is a LTS (long term support) edition of Node. 

But if you have trouble running tests, for now just be sure to have Node v5 or higher. This does not affect actual use of the library at all; just running the tests. 

The error shown is:

```
     ReferenceError: Can't find variable: Bloodhound in file:///home/travis/build/publiclab/PublicLab.Editor/dist/PublicLab.Editor.js (line 22723) (1)
```

**Comment by rexagod** [comment]
> but would like to re-open it because v4.2 is a LTS (long term support) edition of Node.

We can test on Node 8 (also LTS) which I suppose works fine for now. Do open this if there's any need to! Closing this for now.
