### ISSUE TITLE
Window scroll position jumps wildly when typing into bottom of long body of text

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#114]
In Markdown mode, if you go to https://publiclab.github.io/PublicLab.Editor/examples/ and enter a few hundred lines of text -- just paste in a lot -- then type near the bottom, the scroll position starts to jump around, making it very hard to enter text. 

I think this may have to do with the calculation of `scrollTop` on this line:

https://github.com/publiclab/PublicLab.Editor/blob/e74e97ee54fcd01dc81bf4c14cecf6f85cd4cf64/src/modules/PublicLab.RichTextModule.js#L168

`scrollTop` also appears on these lines:

https://github.com/publiclab/PublicLab.Editor/search?utf8=%E2%9C%93&q=scroll&type=

Perhaps we're miscalculating, or maybe we shouldn't try to do this at all? We could test this by manually running setting `document.body.scrollTop` and/or by inserting `console.log` statements by these probable lines, to check when they're being set and by how much.

This needs some exploration to figure out exactly what's causing this!

**Comment by jywarren** [comment]
Related upstream but in Woofmark? https://github.com/bevacqua/woofmark/issues/26

**Comment by kunal-mohta** [comment]
Do you have to resize the the textarea?
If we disable resize, we get this..
![screencast-2018-01-24-01-28-39](https://user-images.githubusercontent.com/30414954/35297838-3f4e58c0-00a6-11e8-9a15-fbbe8bad017c.gif)

..which seems pretty decent.

(My apologies for the poor quality of the gif, you can also view the result in the video present in the zip folder below)
[Screencast 2018-01-24 01:28:39.mp4.tar.gz](https://github.com/publiclab/PublicLab.Editor/files/1657418/Screencast.2018-01-24.01.28.39.mp4.tar.gz)

**Comment by jywarren** [comment]
I think it's just trying to emulate the behavior of the rich text mode... see how it's different there? But maybe if we're seeing bad behavior here we should just disable it for now and ensure it's "pretty tall" ... what do you think?

**Comment by kunal-mohta** [comment]
Oh I see..
I think you are right, instead of disabling resize, we could try to fix the automatic scrolling of the page on entering text, right?

**Comment by jywarren** [comment]
That'd be super. Can you think of a good way forward? Thanks!

On Jan 25, 2018 4:00 AM, "k-cap" <notifications@github.com> wrote:

Oh I see..
I think you are right, instead of disabling resize, we could try to fix the
automatic scrolling of the page on entering text, right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/PublicLab.Editor/issues/114#issuecomment-360402785>,
or mute the thread

**Comment by shapironick** [comment]
+1ing this issue :) as it makes writing intricate notes frustrating.

**Comment by ebarry** [comment]
Hi! I'm also experiencing this. Whenever i do a key command like `⌘b` to bold some text, or click the `B` button, the page positions moves to the bottom of the page -- past the text window all the way to the bottom of the footer. @SidharthBansal do you have any ideas on this?

**Comment by SidharthBansal** [comment]
@ebarry on clicking on the bold button ``B`` I did not notice any movement of the page to the bottom of the page. I also tried with the ⌘b that also works well. I am using Ubuntu with Mozilla Firefox. Maybe the problem is with the browser.

**Comment by ebarry** [comment]
Wow that is great to hear. Can i ask if you tested with several hundred lines of text that caused the entry box to be greatly expanded, like as much as https://publiclab.org/notes/liz/04-24-2018/evaluation-listen4good-round-two-results ?

**Comment by SidharthBansal** [comment]
I tried with the link provided by you but the behaviour is normal.

**Comment by ebarry** [comment]
wow ok! Time to switch to Ubuntu!!! I will try to better document this for other browsers

**Comment by jywarren** [comment]
If you can offer a sample text and step-by-step workflow, we can call in
other people to try it out and report back!

**Comment by ebarry** [comment]
Aha! new information to report: 

in Chrome, when editing a large amount of text, and with a cursor position "below the fold" (somewhere lower than what is shown upon first load of the Editor interface) ---> pressing EITHER the shift key OR the command key (⌘ on mac) causes the page to "move" all the way down to the bottom of the footer, past even the lower boundary of the text box. 

Use this text file for testing (it's the entire content in markdown for https://publiclab.org/notes/liz/04-24-2018/evaluation-listen4good-round-two-results): 
[example text.txt](https://github.com/publiclab/PublicLab.Editor/files/1947278/example.text.txt)

**Comment by jywarren** [comment]
I think we could try to reproduce this by:

1. `console.log()`ing this line to see what the scrollTop values are: https://github.com/publiclab/PublicLab.Editor/blob/e74e97ee54fcd01dc81bf4c14cecf6f85cd4cf64/src/modules/PublicLab.RichTextModule.js#L168
2. instead of pressing `shift` or `command` as Liz says, trying to trigger this by manually entering the same values for `scrollTop` that are being input by the above command, in the JS console
3. observing if this does indeed incorrectly scroll the editor to a bad place as Liz has documented
4. trying to understand why this bad `scrollTop` position is given and in what conditions
5. trying to either stop it from triggering a new `scrollTop` in that moment, or try to get a better value for `scrollTop` when it does.

**Comment by jywarren** [comment]
We can also try to just disable changing `scrollTop` but not disabling the resizing altogether to see if that helps?

**Comment by jywarren** [comment]
@publiclab/soc if anyone likes JavaScript and is looking for a small side project, this one is pretty frustrating if you've ever written a long post on PublicLab.org! Any help appreciated. 😅

**Comment by jywarren** [comment]
We also use the npm module `grow-textarea` to do this, and maybe that's buggy:

https://github.com/publiclab/PublicLab.Editor/blob/e74e97ee54fcd01dc81bf4c14cecf6f85cd4cf64/src/modules/PublicLab.RichTextModule.js#L131-L138

Here are some others we might try: 

* https://github.com/ultimatedelman/autogrow
* https://github.com/jevin/Autogrow-Textarea

**Comment by jywarren** [comment]
I think we have to figure out if the `scrollTop` line is causing this or the `grow-textarea` library. We can try commenting out one or the other and testing this now that Liz has provided a long example text to use.

**Comment by ebarry** [comment]
This is such a funny bug! While editing a long research note, even pressing `Shift` in order to capitalize a letter causes the rapid window scroll to the bottom. As soon as the second letter is typed, however, the window scrolls up rapidly to the correct cursor insert point in the text box (so rapidly, it is not immediately obvious what caused the flicker). Thanks for reading!

**Comment by jywarren** [comment]
I disabled `grow-textarea` on line 136 of `src/modules/PublicLab.RichTextModule.js` and this behavior stopped. So I think it's worth trying a different textarea growing library.

**Comment by jywarren** [comment]
Trying https://www.npmjs.com/package/autogrow now

**Comment by jywarren** [comment]
I've attempted a fix by removing the autogrow feature completely, as suggested by @kunal-mohta. I've commented it out with a note as to why. Tests running...

**Comment by jywarren** [comment]
Merging and publishing

**Comment by ebarry** [comment]
oh wow - SO EXCITED!

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net
