### ISSUE TITLE
Stop fields from jumping around by fixing height of some modules

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#118]
such as the tagging module -- the help text appearing makes it jump - esp on https://publiclab.org/questions/new

also we could do `overflow: hidden` on the rich text module's help area (`class="ple-guide-minor hidden-xs hidden-sm"`) --  but there's no fixed height, so not sure that works

https://publiclab.org/post

**Comment by kunal-mohta** [comment]
Or maybe a solution can be to user `opacity: 0;` instead of `display: none;` for the help text divs.

**Comment by jywarren** [comment]
Ah, interesting -- would you be interested in trying this out and opening a
pull request? We'd love your help.

**Comment by kunal-mohta** [comment]
@jywarren Sure.

**Comment by jywarren** [comment]
Awesome, thank you!!!
