### ISSUE TITLE
Problem with adding code in Rich Editor

### ISSUE THREAD

**Issue by kunal-mohta** [publiclab/PublicLab.Editor#122]
I faced two different issues in two different web browsers while adding code in the Rich editor mode.

### Google Chrome (Version 60.0.3112.113)
This happened when I tried to add code:
![screencast-2018-01-24-21-19-39](https://user-images.githubusercontent.com/30414954/35342278-b26bf252-014d-11e8-9bca-b8758d21ea8b.gif)

### Firefox Developer Edition (59.0b2)
Cursor keeps going on to the beginning of the code snippet on its own:
![screencast-2018-01-24-21-22-07](https://user-images.githubusercontent.com/30414954/35342468-26f4bf96-014e-11e8-9138-dea0ec2a2e5e.gif)

(Videos for the same present in the zip folder below)
[Videos.tar.gz](https://github.com/publiclab/PublicLab.Editor/files/1660535/Videos.tar.gz)

**Comment by jywarren** [comment]
This is a great documentation of an issue. Does this happen on the demo at https://github.com/bevacqua/woofmark ?

**Comment by kunal-mohta** [comment]
No, [woofmark](https://bevacqua.github.io/woofmark/) seems to work as expected.

**Comment by jywarren** [comment]
hmm. i wonder if that's a clue. Any ideas? What woofmark version?

**Comment by sarthak-sehgal** [comment]
@kunal-mohta, @jywarren It works fine on Google Chrome upon pressing Shift+Enter for creating a new line. New `pre` text tags (`<pre></pre>`) are being created upon pressing "Enter" in Google Chrome.
