### ISSUE TITLE
Reposition the bar of editing icons at top of composition box

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#124]
(reposting on behalf of @ebarry from https://github.com/publiclab/plots2/issues/2334)

### Please describe the problem (or idea)

> What problem could this idea solve?

I would like to consider moving the "kitchen sink" bar of editing icons above the text box, currently it is below the text box. 

<img width="699" alt="screen shot 2018-02-15 at 12 03 39 pm" src="https://user-images.githubusercontent.com/161439/36269851-49c8289a-1248-11e8-8899-be537f47586c.png">

I feel there are downsides to having the editing icons below the textbox, namely, that doesn't handle well while scrolling up and down the page, and in cases where the note is long, it's hard to scroll all the way down instead of having it pinned at the top. 

The scrolling issue may also be a related but separate issue, in that the /post and /question page should not be "below the fold" on the average desktop display. These pages should not scroll unless someone drags the composition box to be longer. Let me know if i should break this issue out.  

> What did you expect to see that you didn't?

I would expect to see the editing icons positioned at the top of the text box.

### Please show us where to look

https://publiclab.org/questions
https://publiclab.org/post

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

**Comment by jywarren** [comment]
> The scrolling issue may also be a related but separate issue, in that the /post and /question page should not be "below the fold" on the average desktop display. These pages should not scroll unless someone drags the composition box to be longer. Let me know if i should break this issue out.

I think this does need to be its own issue, and I don't quite follow yet! Thanks!

**Comment by rexagod** [comment]
Found something similar [here](https://github.com/bevacqua/woofmark/issues/64).

**Comment by jywarren** [comment]
Aha! OK, so #127 that Gaurav found does seem like a good solution. What if we came up with a CSS (and maybe JS) solution where the bar is on the bottom of the textarea, but if the bottom of the textarea goes off the screen, the formatting bar gets absolute-positioned and pegged to the bottom edge of the screen?
