### ISSUE TITLE
Detect and add support for people writing markdown

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#125]
(reposting on behalf of @ebarry from https://github.com/publiclab/plots2/issues/2336)

> This is a set of small tweaks -- read to bottom of comments to find the latest mini-project we'd like to add to smooth this experience. Thanks!

### Please describe the problem (or idea)

> What happened just before the problem occurred? 

I am reporting in from a conversation with @shapironick that reveals a lack of support for people writing markdown in the new Editor. The current workflow for someone who wishes to write markdown -- in fact, if they are a long time contributor they probably learned markdown in order to contribute to publiclab.org -- is that they have to click the button ambiguously marked "Rich" at the bottom right of the composition box: 

<img width="699" alt="screen shot 2018-02-15 at 12 03 39 pm" src="https://user-images.githubusercontent.com/161439/36270474-c9e491a2-1249-11e8-8210-fc8f91406db5.png">

I suggest that no one accustomed to writing markdown on publiclab.org would have the faintest idea that -- since updates to our editor -- clicking a button marked "Rich" would be required for their careful formatting to work. As a result, the final published post has had all the markdown formatting "escaped" out with `/`

Trying to fix the formatting without understanding the role of the "Rich/Markdown" button leads to many frustrating cycles of publishing and editing. 

## Possible solutions

Here are a couple ideas: 
* someone writing markdown in the composition box would automatically trigger help text directing the writer to click the button to change the mode to markdown
* change the button text to say "click here to compose in markdown /  click here to compose in Rich Text"

**Comment by jywarren** [comment]
We could scan the input for multiple instances of Markdown-typical characters, like: `##` or `**`, or `](` (commonly part of a Markdown link)

and if it detects them, display an alert below the box? Using a Bootstrap style alert box:

https://getbootstrap.com/docs/3.3/components/#alerts

We could potentially add a line here to check whenever text is entered:

https://github.com/publiclab/PublicLab.Editor/blob/53516c9d827f7952fe1144d428556fd96e03933f/src/modules/PublicLab.RichTextModule.js#L178-L180

And scan through the output of `_module.value()` with a regular expression to find the above strings.

**Comment by jywarren** [comment]
@publiclab/reviewers is anyone interested in digging into a little JavaScript over here? Could this make a good first-timers-only issue perhaps?

**Comment by ebarry** [comment]
I just ran into this issue again, do any @publiclab/reviewers feel like this could make a good issue for a newcomer?

**Comment by jywarren** [comment]
Right on line 179 of the above excerpt we could probably add something like

```javascript
if (_module.value().match("##")) {
  $(_module.options.textarea).after("<div class='alert...");
}
```

**Comment by jywarren** [comment]
And @shapironick -- I think there are possible ways forward for **catching** and correcting markdown use, but it might take some careful mapping out of possible interactions; for example, what if someone really wants to enter `\##` or another auto-corrected string for some reason? And things like that -- the "detect and warn" idea is a good first step and allows us to prove that it works and then add additional next-step features afterwards. 

I opened up a first-timers-only issue here with the changes: https://github.com/publiclab/PublicLab.Editor/issues/129

I've tested these manually; it was a bit more complex than i'd expected but not too bad. I'll try to recruit a new contributor through this and we can see if we can build out the contributor base for this library in particular and maybe get a few other projects done!

**Comment by shapironick** [comment]
sounds good!

**Comment by jywarren** [comment]
OK, this is live -- how's it look? 

http://publiclab.org/post

![screenshot 2018-03-12 at 7 51 29 pm](https://user-images.githubusercontent.com/24359/37315219-ec285c46-262e-11e8-9383-8f9182e64887.png)

**Comment by jywarren** [comment]
Thanks a million to @j-tanz for showing up and fixing this!

**Comment by jywarren** [comment]
Now, when you click `click here`, the above text becomes:

`\## hey there`

Of course from then on it's fixed, but it'd be even better if we could catch that and convert it back to what you'd typed in. 

I think we could do this by fetching: 

```javascript
editor.richTextModule.value().replace(/\\/g,'')
```

That strips out the `\` characters. So, the full command might be:

```javascript
editor.richTextModule.value(editor.richTextModule.value().replace(/\\/g,''));
```

That could be run when you click `click here` -- and the alert window could then be hidden with: `$('.markdown-warning').hide();`

@j-tanz -- any interest in taking on a slightly more complex project? No pressure, but since you're already familiar with this segment of code?

**Comment by ebarry** [comment]
Wow thanks @j-tanz !!! Just followed you on Github.

**Comment by rexagod** [comment]
@ebarry @shapironick @jywarren Is this fixed? I can't see a commit reference or anything from @j-tanz so I'm a little confused as to what needs to be fixed as of now. Please clarify.
