### ISSUE TITLE
Add ability to center text and photos in rich text editor

### ISSUE THREAD

**Issue by shapironick** [publiclab/PublicLab.Editor#126]
a boy can dream!

it would be especially helpful when adding credit to photos so that it isn't easily confusable with the body text.

**Comment by jywarren** [comment]
good idea! I think this would need some kind of markdown syntax for centering... i don't know if that exists... here are some possibilities:

https://stackoverflow.com/questions/3912694/using-markdown-how-do-i-center-an-image-and-its-caption#3955305

https://simplpost.com/markdown.html

This suggested format doesn't work in GitHub Markdown:

`-> Hello world! <-`

We could also try to implement a "caption" element of some kind, which we then use CSS to center.

Or you could in raw mode use the `<center></center>` element -- we could insert that probably, and Markdown would leave it alone -- but it might not be great if that's deprecated in recent versions of HTML...

**Comment by jywarren** [comment]
For anyone hoping to add this feature, here's an example of a new button being added -- for a different feature -- to use as a guide: https://github.com/publiclab/PublicLab.Editor/pull/92/files

**Comment by amitsin6h** [comment]
@jywarren can I work on this as my first contribution.

**Comment by jywarren** [comment]
Hi, @amitsin6h -- this may be a tough one, but if you want to give the `<center></center>` technique a try, we're ready to help you out if you have trouble! Thank you!

**Comment by jywarren** [comment]
Commonmark doesn't specify either a `center` style or a way to add `text-align:center` CSS to a block: https://spec.commonmark.org/0.28/

I can see a couple ways forward:

1. [this suggestion](https://stackoverflow.com/a/43691451/1116657) for images only, not using any Markdown modding
2. we could identify or make a new caption style to make the distinction clear
3. we could use the alt text in the image (the part in the `[alt text]` of `![alt text](image-url.jpg)`) as caption, which we could parse and display below the image -- this might encourage more accessible image posting too for folks who won't see the images

Happy to help on any of these!

**Comment by DivyeshPuri** [comment]
@jywarren Is this issue still active? Can I work on this issue?

**Comment by jywarren** [comment]
yes, we'd love your help!!!
