### ISSUE TITLE
Allow formatting bar in rich text editor to remain in frame while scrolling 

### ISSUE THREAD

**Issue by shapironick** [publiclab/PublicLab.Editor#127]
The formatting bar stays at the bottom of long notes so you have to scroll all the way down to the bottom to use it. If you are doing repeated formatting it can get tedious to highlight the text, scroll down, click the button, scroll up, highlight the text, scroll down etc.

Thank you!

**Comment by jywarren** [comment]
I like this -- @ebarry suggested pinning to top, but we could also have it
"float" at bottom of screen, perhaps...

Recently I've been using the Medium editor and it's quite nice. It has a
"popup" formatter which I think woofmark also supports? Not sure, but it's
surprisingly convenient although actually not a familiar interface.

**Comment by shapironick** [comment]
Oh i like the medium pop up bar too! I think i've seen it (or similar) popping up in unexpectedly conservative places recently (like MS exchange). my only concern would be if it is too limited. I love me some centering and indenting :) 

The medium pop up seems more limited (at least in this incarnation):
![image](https://user-images.githubusercontent.com/7503343/36502434-f83e97d2-1717-11e8-8bad-220cd92e2356.png)

Top or bottom or medium editor pop up all are good from my view as long as the top and the bottom can float and the medium can allow full editing capabilities.

**Comment by jywarren** [comment]
yeah... there's always a balance on options vs. simplicity. Apart from this
issue, what do you think about an "initial" basic toolbar but an expandable
section with more advanced tools? As an independent feature from this
discussion?

**Comment by shapironick** [comment]
That sounds great from my perspective! I don't write as many RNs as I do
emails (maybe I should?) so streamlining isn't as big of a deal here as it
would be on an email editor. I was really bummed when gmail moved all of
the basic text formatting into the expandable section (in place of
promoting products like drive and send $ on the main toolbar) as I use
those tools in

every

 other

email.

:)

**Comment by gauravano** [comment]
Hi @jywarren @shapironick @ebarry does #124 seems to solve this issue(in a way)? Thanks!
