### ISSUE TITLE
Refine user interface design of main image upload

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#148]
When people are prompted to upload a main image, it looks like this: 

![image](https://user-images.githubusercontent.com/24359/42402596-c8b458fc-8149-11e8-9bb5-9c4610b68795.png)

Then when they drag in an image, it looks like this:

![image](https://user-images.githubusercontent.com/24359/42402599-d38ce67c-8149-11e8-955a-03a7fbdf2c40.png)

It can be confusing because you see only part of the image. 

Instead, let's change it to show the whole thumbnail, like this:

![screen shot 2018-07-06 at 6 27 45 pm](https://user-images.githubusercontent.com/24359/42402677-59922f48-814a-11e8-88a8-c03e9744dda7.png)

The code which displays the image once it's uploaded is here: 

https://github.com/publiclab/PublicLab.Editor/blob/e4fcc6b769f3ad81364237924def5bc97db4f015/src/modules/PublicLab.MainImageModule.js#L109

We can use jQuery to display it differently!

**Comment by Rishabh570** [comment]
I would like to work on this :)

**Comment by Rishabh570** [comment]
@jywarren After uploading any picture, thumbnail is not being shown as in above screenshots...is this issue still active?

**Comment by DivyeshPuri** [comment]
@jywarren Is this issue still active. I want to work on it

**Comment by jywarren** [comment]
Hi, sure, but this is a bit open-ended. What do you have in mind?

**Comment by jywarren** [comment]
In the demo, this may not work. But it should work on https://PublicLab.org/post!

**Comment by DivyeshPuri** [comment]
@jywarren I am planning to add CSS to make the image fit to the given box by adding 
`background-position: center;
background-repeat: no-repeat;
background-size: cover;`
This will result in an image appear like the following:
![image](https://user-images.githubusercontent.com/23422478/46434181-86679500-c770-11e8-9723-cef08f40e0f6.PNG)
Before:
![before](https://user-images.githubusercontent.com/23422478/46434215-a7c88100-c770-11e8-9d6a-e174f6270ddd.PNG)

**Comment by jywarren** [comment]
this is great!!! Awesome!
