### ISSUE TITLE
Improve extras section 

### ISSUE THREAD

**Issue by avsingh999** [publiclab/PublicLab.Editor#157]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
https://publiclab.github.io/PublicLab.Editor/examples/ in here is extras section at the bottom but it's not looking good for short resolution window and
![extras](https://user-images.githubusercontent.com/25536022/46312917-1e844380-c5e4-11e8-9e7d-9ca11476c5a9.png)

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 

make mobile repsonsive extras section, using Bootstrap to hide the button text but not the icon (only at lower screen widths!)

Code links….
https://github.com/publiclab/PublicLab.Editor/blob/e4fcc6b769f3ad81364237924def5bc97db4f015/examples/index.html#L171

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by avsingh999** [comment]
@jywarren please can you tell me what is the uses of extras section because if we click on then nothing to happen thank you

**Comment by jywarren** [comment]
It's an example of how we might integrate future features!  But doesn't
have to work in the demo :-)

**Comment by avsingh999** [comment]
@jywarren  ok thank you 
can you please now check this issue is valid or not I have edited it thank you

**Comment by jywarren** [comment]
Yep this is fine -- I suggest using Bootstrap to hide the button text but not the icon:

https://getbootstrap.com/docs/3.3/

**Comment by jywarren** [comment]
(only at lower screen widths!)

**Comment by avsingh999** [comment]
@jywarren  you are right, should only show icon in lower screen widths

thank you

**Comment by avsingh999** [comment]
@jywarren  please review this issue i have edited and make for GCI-candidate

thank you

**Comment by SidharthBansal** [comment]
Great work

**Comment by avsingh999** [comment]
This task is published on GCI dashboard. Thanks all.
