### ISSUE TITLE
Filter out or prevent empty bold tags in WYSIWYG (woofmark)

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#162]
Often when bolding things in the WYSIWYG module, empty bold markdown gets saved, resulting in sections like this which no longer even render as Markdown:

```
An initial paragraph

**
**

**A real bolded section here**

Continue with another paragraph
```

We should try to catch and filter out this:

```
**
**
```

perhaps within the module (as future WYSIWYG alternative modules may not share this bug). This should be pretty easy to detect and filter!

**Comment by subhahu123** [comment]
give some screenshot or more explanation about what are u taking about
@jywarren

**Comment by jywarren** [comment]
Sometimes when pasting or adding bold text in the wysiwyg mode, extra empty
bold tags get generated. Maybe I should make a screencast?
