### ISSUE TITLE
Write test for dataurl-detection feature

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#181]
We have a great new feature to detect and warn about data urls -- #178. I'm also wondering if we could add a test for this behavior. We could paste a small dataurl into the codebase and then check for the alert to be shown. We could do something pretty simple -- see this for entering something into the rich text module textarea:

https://github.com/publiclab/PublicLab.Editor/blob/19a379062304fabc6e280f4915a5f5a889c2595b/spec/javascripts/rich_text_module_spec.js#L36

```js
 module.value('Test text'); 
then we could do expect($('.alert.data-urls-warning').length).toBe(1);
```

However, @okonek said that:

> Yes, I tried $().trigger("keydown"), but it did not succeed, also I searched in the other tests for some similar code, but I did not find any.

So the test @okonek tried is not yet working, but if we can trigger the "click" event somehow we should be able to finish this. @okonek would you mind sharing the test you wrote so far? Thanks!!!

**Comment by rexagod** [comment]
Hmm. Maybe something like this may be of help :thinking: 
````js
    //enter data:image/x
    module.value('data:image/x')

    //simulate enter press
    var e = jQuery.event('keydown')
    e.which = 13
    _module.wysiwyg.editable.trigger(e)

    //detect data-urls
    expect($('.data-urls-warning').length).not.toBeNull()
````
I'll check this out. In the meantime, @jywarren, can you review my pending PRs?
