### ISSUE TITLE
Make testing cover the build process "grunt build"

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#196]
This will help address #195 

We need to get our tests to run `grunt test` and pass only if that completes. Then we'll be able to more confidently merge @dependabot updates that address build code such as Browserify in #163.

@rexagod would you have any interest in trying to get this working? I think it'd be an adjustment to the Gruntfile. We'd want to first confirm that a failed build results in Travis reporting a build failure. 

Thanks!!!

**Comment by rexagod** [comment]
[Failed build now results in a "failed prompt"](https://travis-ci.org/publiclab/PublicLab.Editor/jobs/475590529#)
