### ISSUE TITLE
Replace 'rake test' with 'grunt jasmine' in PR template

### ISSUE THREAD

**Issue by geekychaser** [publiclab/PublicLab.Editor#219]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** Update PR template with `grunt jasmine` instead of `rake test`

![image](https://user-images.githubusercontent.com/24489162/51036658-c80ba580-15d3-11e9-932a-cb5e32d04f8b.png)

**code link** : https://github.com/publiclab/PublicLab.Editor/blob/master/.github/PULL_REQUEST_TEMPLATE.md

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by jywarren** [comment]
This is fantastic!

**Comment by geekychaser** [comment]
Yes now yo can post a PR from your forked one

**Comment by Wesbest** [comment]
I am not sure what you exactly mean with that. Do you mean I need to transfer the PR from my fork to the your repository? If yes how do I do that?

**Comment by Wesbest** [comment]
@rexagod thank you for your reply. when I fetch this repo and check the git status it says:
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

So I guess only my work needs to be pushed but I have not granted access to that. Am I going in the right direction so far?

**Comment by geekychaser** [comment]
@wesbest Great you are going right. Now you need to post pull request from your forked repository.

**Comment by Wesbest** [comment]
Okay when I tried to push my work it says permission not granted to your repo. Also see pic below. I am a little confused on how it all should go.
![screenshot from 2019-01-12 11-16-09](https://user-images.githubusercontent.com/46609675/51072121-6d199300-1653-11e9-854e-7ad06091e0c8.png)

**Comment by rexagod** [comment]
@Wesbest You're all set! Just `create pull request` so that we can review and merge your first PR!

Thanks!

**Comment by Wesbest** [comment]
Thanks for helping all :). I think I did it.

**Comment by geekychaser** [comment]
@Wesbest No problem, Great job!
