### ISSUE TITLE
Editor controls overlay.

### ISSUE THREAD

**Issue by himanshuc3** [publiclab/PublicLab.Editor#228]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
![screenshot 2019-01-14 at 11 52 18 am](https://user-images.githubusercontent.com/19166045/51098917-83f6eb80-17f3-11e9-989b-d78b1bedd15f.png)

> What did you expect to see that you didn't?
Editor toolbar hidden or attached to the top of history tab.

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?
himichhabra14
> This can help us diagnose the issue: 
Scrolling to the bottom of the page.

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
Chrom v71

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
Hi @himanshuc3 thanks for reporting the issue. This issue has been converted to a FTO at #231 and a PR is also in-progress.
