### ISSUE TITLE
Update Pull Request template

### ISSUE THREAD

**Issue by rexagod** [publiclab/PublicLab.Editor#230]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: Replace `@publiclab/reviewers` by `@publiclab/reviewers and @publiclab/is-reviewers`.

**code link** : https://github.com/publiclab/PublicLab.Editor/blob/master/.github/PULL_REQUEST_TEMPLATE.md

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
Hi @rexagod, @publiclab/is-reviewers group is only for only for Image-Sequencer. So, there is no need of this issue for now. Thanks!

**Comment by rexagod** [comment]
Oh sorry about that @gauravano! Didn't know about that. Although I see that currently only `@publiclab/is-reviewers` is mentioned in the PR template there. Can I open this issue there requesting addition of `/reviewers` too? Or is it good as is?

**Comment by gauravano** [comment]
yes, this issue will fit there. Thanks!

**Comment by rexagod** [comment]
@gauravano done! Can you go ahead and label [this issue](https://github.com/publiclab/image-sequencer/issues/672) as an `fto`? Thanks!!
