### ISSUE TITLE
Github Pages build failure

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#238]
@sagarpreet-chadha @rexagod after merging the new Map module, i got this error from GitHub when it tried to build the gh-pages online demo... any ideas?

```
The page build failed for the `gh-pages` branch with the following error:

The symbolic link `/node_modules/.bin/grunt` targets a file which does not exist within your site's repository. For more information, see https://help.github.com/articles/page-build-failed-symlink-does-not-exist-within-your-site-s-repository/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds
```

**Comment by rexagod** [comment]
> When in local mode, executables are linked into ./node_modules/.bin so that they can be made available to scripts run through npm. (For example, so that a test runner will be in the path when you run npm test.)

Hi @jywarren. I think this is because of the `node_modules/.bin/grunt` file that currently includes `require('grunt-cli/bin/grunt')`. [Didn't you remove this from the build process](https://github.com/publiclab/PublicLab.Editor/pull/211#issuecomment-454211307)? Maybe clearing out the `.bin` and `npm install` again should fix this.

**Comment by sagarpreet-chadha** [comment]
Yes @rexagod @jywarren ! 
Happened with me in LEL , i re-installed all dependencies and then pushed again to `gh-pages` 👍 .

**Comment by rexagod** [comment]
@jywarren Grunt and all the removed devDeps need to be removed from here too, or else it'll keep including them in `.bin` everytime it builds.
https://github.com/publiclab/PublicLab.Editor/blob/e24a5948e2cfdaed89895536f00ff6ea657bc449/package.json#L46-L57

**Comment by rexagod** [comment]
@jywarren Can we close this now?

**Comment by jywarren** [comment]
do we need to make the changes to devDeps first? Thanks!

**Comment by rexagod** [comment]
Removed all Grunt devDeps and Jasmine. Is this okay @jywarren?

https://github.com/publiclab/PublicLab.Editor/blob/987f5f73b11bc4745ea0d0c6634ae5ca95742466/package.json#L46-L49

**Comment by rexagod** [comment]
No worries @jywarren! Closing this now. :+1:
