### ISSUE TITLE
Icon images in toolbar appear broken

### ISSUE THREAD

**Issue by IgorWilbert** [publiclab/PublicLab.Editor#240]
### Please describe the problem (or idea)

The image icons in the toolbar and other buttons appear broken after simply running `grunt build` and opening `/examples/index.html`, nothing else.
![bug](https://user-images.githubusercontent.com/42987854/51419121-235b0c00-1b6f-11e9-8aa1-adea699fc3c4.JPG)

The image icons should appear normal, just like in the demo version.
![right](https://user-images.githubusercontent.com/42987854/51419155-51405080-1b6f-11e9-8d2d-7a25b1f84cd3.JPG)

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

Windows 10, Firefox Quantum 64.0.2

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sagarpreet-chadha** [comment]
Hi all !
Most probably it is due to CORS issue of font-awesome (you may see the
console in your browser for more detailed error describtion) . Thanks !

**Comment by rexagod** [comment]
@sagarpreet-chadha How about storing a local copy of font-awesome on the repo so we don't face such issue? @IgorWilbert could make a `fto` on that instead. What do you think?

**Comment by IgorWilbert** [comment]
Hey @rexagod ,  I proceeded the installation steps from README, opened the project in my terminal, ran `grunt build` and opened `examples/index.html`. @sagarpreet-chadha yes, indeed there's an error in the console: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///C:/Users/igorh/Documents/GitHub/Public%20Lab/PublicLab.Editor/node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0. (Reason: CORS request is not HTTP).` @rexagod turning it into a `fto` sounds nice, I'd like to do that! :)

**Comment by gauravano** [comment]
Hi @IgorWilbert, you can add it as information so that new contributors don't face such issues. And, it's worth opening issue, we always discover a new problem or effective solution. Thanks!
