### ISSUE TITLE
Fix zIndex properties

### ISSUE THREAD

**Issue by rexagod** [publiclab/PublicLab.Editor#246]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: One can easily encounter the following formatting problem.

![screenshot from 2019-01-22 02-34-41](https://user-images.githubusercontent.com/33557095/51499004-ab027e00-1dee-11e9-8d13-f32381fa5656.png)

To fix this, we'll break this into two steps. First, we'll need to set the `z-index` property of the `wk-prompt` to some high value (eg., 999) so that it always stays on the top. We can do this by changing the value of `z-index`below to, say `999`.
https://github.com/publiclab/PublicLab.Editor/blob/1584378fa079c98209ef34bea2b1688ad82bc6d6/dist/PublicLab.Editor.css#L155-L159
Second we need to fix the current overlapping of the `wk-commands btn-group` with the above `wk-prompt` dialog box. To do this, we can replace the `z-index` value here to something lower, say 2.
https://github.com/publiclab/PublicLab.Editor/blob/1584378fa079c98209ef34bea2b1688ad82bc6d6/src/modules/PublicLab.RichTextModule.js#L263

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by spelgubbe** [comment]
I can do this

**Comment by gauravano** [comment]
Go ahead @spelgubbe! Thanks!

**Comment by spelgubbe** [comment]
Can someone review this? I haven't done a pull request before but it looks like it worked... #248
