### ISSUE TITLE
Publish button doesn't go back to disabled state if user clears Title text

### ISSUE THREAD

**Issue by vrk99** [publiclab/PublicLab.Editor#250]
### Please describe the problem (or idea)

Currently, if the title is empty then the "Publish" button is disabled
![screenshot from 2019-01-23 20-26-39](https://user-images.githubusercontent.com/31163120/51616026-44e13c80-1f4f-11e9-8998-4fdf9726dfb3.png)

And if a user enters the title then it becomes enabled, as expected
![screenshot from 2019-01-23 20-27-04](https://user-images.githubusercontent.com/31163120/51616464-2760a280-1f50-11e9-82b2-6fb04bbc6124.png)

But after doing so, if the user later clears the Title, the button remains in enabled state even though there are "1 of 2 steps left"
![screenshot from 2019-01-23 20-27-25](https://user-images.githubusercontent.com/31163120/51616575-64c53000-1f50-11e9-97e1-4fd228944707.png)

If this is not an issue with just my local setup, then i think this would be a small design fix.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by vrk99** [comment]
> Hi @vrk99, we are discussing about this issue some days ago - [#37 (comment)](https://github.com/publiclab/PublicLab.Editor/issues/37#issuecomment-450720788). Thanks for opening detailed issue. Also, would you like to solve this one?
> 
> Thanks!

Oh, sorry I didn't already notice that issue.
Yeah, I would like to try solving it.

**Comment by gauravano** [comment]
No need to be sorry, as we should've opened an issue at that time only, but anyways thanks for helping with this one.

**Comment by niravasher** [comment]
Hi! Is this issue solved? If not I think I can solve this @gauravano @vrk99

**Comment by vrk99** [comment]
> Hi! Is this issue solved? If not I think I can solve this @gauravano @vrk99

Hey @niravasher , I have already made a PR and just waiting for the final review.

**Comment by gauravano** [comment]
@niravasher you can find more issues to work at https://code.publiclab.org/#r=all . Thanks!
