### ISSUE TITLE
Use accept attribute for Main Image Upload

### ISSUE THREAD

**Issue by vrk99** [publiclab/PublicLab.Editor#254]
### Please describe the problem (or idea)

> This is a minor Suggestion.

While we are validating the file uploaded for its image format server side, we could set the default upload type to images using accept attribute for the client.

Currently on clicking Choose File for image upload, the user can see all the files; Something like this:
![screenshot from 2019-01-24 18-15-03](https://user-images.githubusercontent.com/31163120/51679812-f478e600-2005-11e9-8036-ff0086e03940.png)

We could instead set default to jpg, jpeg, png and gif using accept attribute. The result for the same folder will then be:
![screenshot from 2019-01-24 18-10-23](https://user-images.githubusercontent.com/31163120/51679888-28eca200-2006-11e9-91e2-9c66fa5d4918.png)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by rexagod** [comment]
I think we should let this be as is for the moment as explicitly hardcoding the formats may not prove to be a good idea with time if the formats differ (eg., BMPs, SVGs, etc) and we'll have to keep those updated. But at the same time this could add to the convenience factor of the Editor and prevent unnecessary failures and crashes. @gauravano thoughts?

**Comment by gauravano** [comment]
Using "Choose File" button at publiclab.org/post allow choosing only image files only, but Drag and Drop takes different file formats such as pdf, xlsx. etc. I haven't checked code but tried at production and seems like constraints are handled. 

Have you checked at production? Thanks!

**Comment by vrk99** [comment]
I inspected the publiclab.org/post page and the accept attribute is present there:
![screenshot from 2019-01-25 17-52-34](https://user-images.githubusercontent.com/31163120/51745994-ac6fc700-20ca-11e9-831d-6fc8ee7e5131.png)

But if i am not wrong the current code in this repo does not:
https://github.com/publiclab/PublicLab.Editor/blob/94a549c6e6fcbc0d5ef8e6e3ebbf6322b46e748a/examples/index.html#L108

If we want this behaviour then it is a simple fix; i could resolve this. Or else if we want to keep it as it it as @rexagod suggested then i guess we can close this issue for now.

**Comment by niravasher** [comment]
Hello! I am working on this issue

**Comment by vrk99** [comment]
Ok, No Problem.
But did @rexagod or @gauravano confirm this as a relevant issue? Coz the last thing I know is that we were discussing whether to solve this issue or close it and let the feature as is.

**Comment by gauravano** [comment]
@jywarren you think it's required, as we are using accept-attribute at plots2, so it's sufficient? Thanks!

**Comment by niravasher** [comment]
There is a slight change in the syntax. The exact syntax is
<input type="file" name="pic" accept="image/*">
I am not sure if both the methods are same. Please help me out here @vrk99 @rexagod @gauravano

**Comment by rexagod** [comment]
We certainly can add a `accept="image/*"` attribute for the main _image_  upload here. Also, I do believe this would not allow the user to upload anything other than an image hence being a better measure. So I think you should proceed with this. Thanks!

**Comment by rexagod** [comment]
@gauravano I think this can easily be converted to an `fto`. What do you say?

**Comment by gauravano** [comment]
Go ahead!


Gaurav Sachdeva

**Comment by rexagod** [comment]
Done! #274 

Closing this now.
