### ISSUE TITLE
Contrasting address bar support

### ISSUE THREAD

**Issue by rexagod** [publiclab/PublicLab.Editor#259]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: All we need to do here is add the following line in the `<head>`, `<meta name="theme-color" content="#000">`. This would help the mobile chrome viewscreens to adapt to a better contrast theme for the Editor, hence improving readability and user engagement.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by rexagod** [comment]
@gauravano We'd love to have you start away on PL.Editor! However, if you want to assign someone else to this issue, feel free to do so. Thanks!

**Comment by gauravano** [comment]
Thanks @rexagod!@niravasher you wanna claim this?

**Comment by rexagod** [comment]
@gauravano If I may weigh in here, I think @niravasher already has an ongoing PR at https://github.com/publiclab/PublicLab.Editor/pull/255, and has been comfortably communicating his ideas on many different issues for a while now. If it's fine by you, I'd recommend to assign this to someone new with zero experience about the PL.Editor environment, so that they can get upto speed in no time, hence helping a potential contributor too. But I also understand if for some reason you would still like to assign this to @niravasher. 

Both options and fine by me.

**Comment by anto004** [comment]
Hi, can I take this one?

**Comment by gauravano** [comment]
Hi @anto004, sure go ahead!

Hi @rexagod, actually @niravasher asked me for an first-timer-only so after going through then opened FTO's, I found that @askshaygupta553 also needs one, so asked him. And, thanks for creating FTO at such a short notice. If you see any possible issue which can be a good FTO, please tag @akshaygupta553 there, as he might be interested in solving one. 

Thanks!

**Comment by rexagod** [comment]
@gauravano Made one @ #261

**Comment by gauravano** [comment]
Thanks @rexagod !

**Comment by rexagod** [comment]
No problem @gauravano.

**Comment by sog01** [comment]
Is still opened ?

**Comment by gauravano** [comment]
Hi @sog01, PR for this issue is already in progress, so please take a look at other issues at https://code.publiclab.org/#r=all. Thanks!

**Comment by rexagod** [comment]
@sog01 There's a `fto` open [here](https://github.com/publiclab/inline-markdown-editor/issues/40) if you're interested. Thanks!

**Comment by sog01** [comment]
Wow thanks @rexagod, I will look into this.

**Comment by lohitha02** [comment]
Hello is someone working on this issue?

**Comment by gauravano** [comment]
yes @lohitha02, it has a PR in progress at #264

**Comment by Srija616** [comment]
Hey! I am an Outreachy applicant. Can I work on this issue?

**Comment by debck** [comment]
Sorry, this issue is already fixed at #264 .
Closing this
