### ISSUE TITLE
Designing a manifest for PL.Editor

### ISSUE THREAD

**Issue by rexagod** [publiclab/PublicLab.Editor#261]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: In this `fto`, you will need to design a `mainfest.json` for a mobile-rich experience of the PL.Editor. Take some time to understand the theme and design of the [Editor](https://publiclab.github.io/PublicLab.Editor/examples/), and [design a `mainfest.json`](https://developer.mozilla.org/en-US/docs/Web/Manifest) file that you think will suit best to the Editor.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by rexagod** [comment]
@gauravano You can assign @akshaygupta533 here if you like.

**Comment by rexagod** [comment]
@IgorWilbert I did include a MDN link where anyone can easily understand the procedure of creating a `manifest` so I didn't feel the need to explicity include it in the description. However, if you'd like to, you can create a new `fto` with the details and I'll close this one. :+1:

**Comment by IgorWilbert** [comment]
@rexagod sorry, I didn't notice. Yes, with the MDN link creating the `manifest` seems pretty straightforward. By the way, I updated the code and included an image in #244 , looking forward to hear your thoughts :)

**Comment by robert-aron** [comment]
Hey, can I give this a try?

**Comment by rexagod** [comment]
Sure, go ahead @robert-aron!

**Comment by robert-aron** [comment]
@rexagod Just a question, where is the manifest.json file supposed to go? I put it in /examples/data/ but I'm not sure if that's the right place.

**Comment by rexagod** [comment]
I suppose we can place it there and copy the relative path in the index.

**Comment by akshaygupta533** [comment]
Sorry got a bit busy @rexagod. Is there anything else I can work on?

**Comment by robert-aron** [comment]
@akshaygupta533 Oh sure, go ahead. Also I can give you the manifest file I wrote if you want it

**Comment by akshaygupta533** [comment]
Yes please.

**Comment by akshaygupta533** [comment]
On second thoughts, I will try doing it on my own. Thanks anyways :smile:

**Comment by rexagod** [comment]
Thank you @robert-aron for assigning this to @akshaygupta533. Please go ahead and check-out the `fto`s [here](https://github.com/publiclab/inline-markdown-editor/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+*.md) for submitting your first PR!

Thanks!

**Comment by cesswairimu** [comment]
Hi, I think this may be unnecessary for the examples demo use case -- but it's a good idea overall! Maybe, consider reopening this on the `plots2` repository? https://github.com/publiclab/plots2 

Thank you!!!!

_Originally posted by @jywarren in https://github.com/publiclab/PublicLab.Editor/pull/263#issuecomment-648878397_
