### ISSUE TITLE
Redesigning the UI of the main website of publicLab

### ISSUE THREAD

**Issue by niravasher** [publiclab/PublicLab.Editor#262]
### Please describe the problem (or idea)
I believe that the main website can be more interactive and more catchy to the users eye

### Please show us where to look

https://publiclab.org/

### What's your PublicLab.org username?
niravasher

### Browser, version, and operating system
Windows 10

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
There are 16 different links on the website, when clicked go to the same page. Top nav can be improved and fonts and the method of presentation of images along with their description could be better. I could also make a nodejs chatbot and stick it to the bottom right of the page for better interaction. I am in the process of designing the page and post it in the comments section once its ready. An intro video can also be included. This is my proposal for a GSOC 2019 project. If it seems vague to the community, then please close the issue.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by rexagod** [comment]
@niravasher Since this one is related to the website, I suggest you open this on the PLOTS2 repository as @IgorWilbert recommended above. I'm closing this for now.
