### ISSUE TITLE
Apparently unused buttons in the toolbar

### ISSUE THREAD

**Issue by IgorWilbert** [publiclab/PublicLab.Editor#265]
### Please describe the problem (or idea)

These four buttons do nothing on click on my setup. It might be because I'm only using `npm live-server`, not connected to plots2. I believe one should be used to add another grid with certain rows/columns and other should be used to upload videos. Also, they could have a pop up description on hover, like the ones beside them.

![issue](https://user-images.githubusercontent.com/42987854/51859462-4f6c4f00-231e-11e9-9c44-189f216db79b.JPG)

### Please show us where to look

Just open the editor and click on the buttons highlighted on the image.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by IgorWilbert** [comment]
@rexagod @gauravano what are these buttons used for? Are they all working properly? If yes I would be happy to **add a description for each of them on mouse hover and turn this into a FTO-issue** :)

**Comment by rexagod** [comment]
Hello Igor! The buttons work fine as of now. I've tested them below. Do let me know if there's any other issue? Closing this for now.

![peek 2019-01-29 02-29](https://user-images.githubusercontent.com/33557095/51866019-ce3ca880-236d-11e9-952f-db82cdc96ae8.gif)
