### ISSUE TITLE
remove requirement of BlurredLocation library if we're not using the Map Module

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#268]
It looks like the new Map module requires Leaflet.BlurredLocation, as here:

https://github.com/publiclab/plots2/blob/7c1ef45e307a0771a5cbd805b7c6947034bb061b/app/views/editor/questionRich.html.erb#L8-L12

I had to add it there even though we don't use that module in the question form, so I was wondering if we could adjust the code to not require it unless the module is actually used. @sagarpreet-chadha and @rexagod maybe you could help me out? Then we could revert the change I just made to the question form code, and it'd be a bit tidier!

For reference, see the error we got in https://github.com/publiclab/plots2/issues/4742 when we didn't include the dependencies in the HTML page. 

Thanks, all! 👍

**Comment by rexagod** [comment]
As of now, [`/questions/new`](https://publiclab.org/questions/new) isn't working, as the `Map` container isn't implemented on the same page, according to the logs, so I think we should get the `master` back up as soon as possible.

![map](https://user-images.githubusercontent.com/33557095/52113337-0c1c2400-262f-11e9-91eb-0c8e7b858e43.gif)

@jywarren @sagarpreet-chadha

**Comment by jywarren** [comment]
OK, saw that and fixed it just now. The most recent commit fixes it (i hope) but the one before it is for adding the BlurredLocation library -- https://github.com/publiclab/plots2/commits/master/app/views/editor/questionRich.html.erb

Thanks for helping debug. Ideally neither would be needed if we're not using the module...

**Comment by jywarren** [comment]
Publishing ASAP to production...!

**Comment by jywarren** [comment]
Thanks for the fast response @rexagod - sorry i think i was asleep by the time you posted.

**Comment by jywarren** [comment]
that fixed it!

**Comment by rexagod** [comment]
I think changing `_editor.options.mapModule !== false` to `_editor.options.mapModule === true` 
should fix this. This checks out on local btw.

https://github.com/publiclab/PublicLab.Editor/blob/5d0ec89f30f760aa9df413ef34a983f3a73db503/src/PublicLab.Editor.js#L210
