### ISSUE TITLE
Attach file window gets overlayed on scroll.

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/PublicLab.Editor#273]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

When one scrolls the window, the attach window gets obstructed by the options of the Public Lab Editor.

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sidntrivedi012** [comment]
![attachwin](https://user-images.githubusercontent.com/31186013/52162071-819df800-26f4-11e9-90d0-24d88c9ee092.gif)
@jywarren Please take a look.

**Comment by rexagod** [comment]
@sidntrivedi012 Have you verified this on local?

**Comment by IgorWilbert** [comment]
@rexagod @sidntrivedi012 I checked this on local and wasn't able to reproduce the bug. My setup: windows 10, Firefox Quantum 65.0 (64-bit).

**Comment by gauravano** [comment]
I checked on Production, can't reproduce it

![no_overlay_editor](https://user-images.githubusercontent.com/20878070/52583264-2c30bc00-2e55-11e9-81e4-65be52f0e499.gif)

@sidntrivedi012 maybe the issue is solved in last push to production. Can you try one more time on your end? Thanks!

**Comment by sidntrivedi012** [comment]
Sure! Will try on the local again and close the issue if it's resolved. :)

**Comment by gauravano** [comment]
Great!

**Comment by sidntrivedi012** [comment]
@gauravano Yes, it's working fine on local. Closing the issue for now. But, why is it now working on the production side?

**Comment by gauravano** [comment]
Maybe some recent push to production solved this issue :thinking: .
