### ISSUE TITLE
"Use current location" button hides editor text formatting buttons

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#281]
Oops, very small issue @sagarpreet-chadha -- clicking this button makes the text formatting buttons disappear -- looks like just a small jQuery selector over-reach:

![image](https://user-images.githubusercontent.com/24359/52382554-b0dd9d80-2a43-11e9-8ac0-86893cef2fc8.png)

**Comment by jywarren** [comment]
Would you mind taking a look? I bet it's when it removes the spinner icon!

**Comment by sagarpreet-chadha** [comment]
Yes on it :+1:  !

**Comment by sagarpreet-chadha** [comment]
Okay solved in PR : https://github.com/publiclab/leaflet-blurred-location/pull/177 .
