### ISSUE TITLE
Add a test for Publish button disabled state

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#295]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

We just had an issue with PublicLab.org/post not un-disabling the button state, because the way the button worked changed. I've just fixed this in eaa18bb8fa3345893ed06feda0f807a72dc6af19, but thought we should make a test at least so we know when there are breaking changes. Thanks!

**Comment by jywarren** [comment]
This could be a nice first-timers-only, if we point at an existing test we copy, like this one:

https://github.com/publiclab/PublicLab.Editor/blob/b948d2f543a1c5b38fcb13f190d8676cd29ea9fb/spec/javascripts/errors_spec.js#L6-L22

We could make a copy where we ensure the inputs for title and body are empty, then we could add an `expects()` asserting that:

```js
// before:
expect($('.ple-publish').addClass('disabled')).toBe(true);
expect($('.ple-publish').prop('disabled')).toBe(true);

// add a title:
$('.ple-module-title input').val('A title');
$('.ple-module-body textarea').val('Body text'); // ensure we're in markdown mode, though!

// after:
expect($('.ple-publish').addClass('disabled')).toBe(false);
expect($('.ple-publish').prop('disabled')).toBe(false);
```

**Comment by manansingh96** [comment]
I would like to try this.

**Comment by gauravano** [comment]
Go ahead @manansingh96! Thanks!

**Comment by manansingh96** [comment]
@gauravano I am not very good with tests as I don't have much experience. I wasn't able to do this. I would like some help.

**Comment by gauravano** [comment]
Hi @rexagod @IgorWilbert, could you please help @manansingh96 with this issue? Thanks!

**Comment by rexagod** [comment]
Hi @manansingh96! Writing tests for PL modules isn't hard at all, and below are some resources to help you through it!

Here's a commit to get you started: https://github.com/publiclab/PublicLab.Editor/pull/220/files#diff-d7c7c4e4627e0374a41634bef6978dc6
Jasmine (our current testing framework) docs: https://jasmine.github.io/2.0/introduction.html

Do let us know if you face any problems whatsoever! Thanks!!

**Comment by swathi-0901** [comment]
hello, I would like to work on this issue can @gauravano tell me what is supposed to be done? Thank you:)
