### ISSUE TITLE
Add reference to Github repository

### ISSUE THREAD

**Issue by IgorWilbert** [publiclab/PublicLab.Editor#297]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: this will add a link to the Github repository and Public Lab's website in the header, just like the ones in image-sequencer. All that needs to be done is paste this code:

        
      <p>
        Open Source
        <a href="https://github.com/publiclab/PublicLab.Editor">
          <i class="fa fa-github"></i>
        </a>
       by <a href= "https://publiclab.org" title = "Public Lab website"><i class = "fa fa-globe"></i> Public Lab</a>
      </p>

Right below this line:
https://github.com/publiclab/PublicLab.Editor/blob/f3e5ecf37f86dee0fe4cf09970eb93643b9c6add/examples/index.html#L95

So that it should look like this:

![pic](https://user-images.githubusercontent.com/42987854/53695692-7f839380-3d9d-11e9-8575-a18a0b6b9043.JPG)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by marieram** [comment]
Hi. Can I work on this?

**Comment by IgorWilbert** [comment]
@marieram sure, go ahead!

**Comment by manansingh96** [comment]
I am new. Someone has claimed it above. So, I shouldn't work on this?

**Comment by rexagod** [comment]
@IgorWilbert I suppose @manansingh96 can take up this issue since @marieram has previously opened some PR(s) in PL.

**Comment by IgorWilbert** [comment]
Sure @rexagod ! @marieram would you mind leaving this one for @manansingh96 ? Sorry about the mess, thanks!

**Comment by marieram** [comment]
No worries, I understand!

**Comment by manansingh96** [comment]
@marieram Thank you!

**Comment by manansingh96** [comment]
@IgorWilbert I have created a pull request. #298 

Please review. Thanks.
