### ISSUE TITLE
in-richTextModule autocomplete via bevaqua/horsey

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#3]
of usernames, tagnames, research notes by id or title (like github issues?) -- maybe another syntax like `P#` or `$` or `[title]`?

**Comment by gauravano** [comment]
@jywarren I think adding more information and details to this can convert it to a project. What do you think?

**Comment by jywarren** [comment]
I believe we can merge this into #44 which has been shown to work more reliably as an alternative approach!
