### ISSUE TITLE
Multiple font awesome loading icon in maps module .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/PublicLab.Editor#305]
### Please describe the problem (or idea)

In map module , when we use the **Use Current Location** button and if user denies permission to give her location , the spinner still persists . 

Moreover if we click again the button and again user denies access to location , there comes 2 spinners . 
<img width="890" alt="Screenshot 2019-03-16 at 2 02 12 PM" src="https://user-images.githubusercontent.com/14952645/54472780-7dd1bb00-47f4-11e9-936e-f4245e1f2262.png">

### Solution 

Let's remove the spinner if : 
1.) User denies to give access to her location . 
2.) If by default the browser settings do not allow access to location .

****

**Comment by DevanshCodes** [comment]
Hey! can I work on this?

**Comment by shreyaa-s** [comment]
Hey @sagarpreet-chadha , I'm an outreachy applicant and i would like to work on this issue if it is up for grabs. Can you please assign it to me? Thanks!
