### ISSUE TITLE
Table template maker seems broken

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#309]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Not a huge deal, but just documenting for future fixes -- looks like somehow our "table template generator" which was already imperfect, but kind of handy, has broken:

![image](https://user-images.githubusercontent.com/24359/54780726-df2ccc00-4bf0-11e9-8a5a-345942e83773.png)

It used to show 2 inputs that you could put numbers into for your # of columns and rows, and it would generate a table. Code is here:

https://github.com/publiclab/PublicLab.Editor/blob/master/src/modules/PublicLab.RichTextModule.Table.js

If anyone got interested in fixing this, it'd be great! Thanks!

**Comment by manansingh96** [comment]
I did try working on this(wasn't able to invest much time due to illness), I even updated it in a previous Issue [here](https://github.com/publiclab/PublicLab.Editor/issues/302#issuecomment-470605429). 

I tried the same code on jsfiddle and it works perfectly.
It's a very weird issue.

@jywarren

**Comment by jywarren** [comment]
oh thank you! I'm sorry to hear of your illness.

**Comment by SidharthBansal** [comment]
PUBLISHED to GCI dashboard
