### ISSUE TITLE
Selecting numbers after using bullets changes old bullets

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/PublicLab.Editor#312]
![Peek 2019-03-21 22-58](https://user-images.githubusercontent.com/30197132/55022633-fd476180-5020-11e9-9f3b-22aef1bf1af2.gif)

**Comment by auralshin** [comment]
I  would like to work on this

**Comment by Parth910** [comment]
@kaustubh-nair this is not an issue now.so you can close this issue.
