### ISSUE TITLE
Scroll problem in text editor

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/PublicLab.Editor#313]
### Please describe the problem (or idea)

> [x] What happened just before the problem occurred? Or what problem could this idea solve?
There must be a seperate scroll view for the text editor. When we scroll the area in text editor, entire page is scrolled. This is just the problem with the rich text area part, not with the markdown part. 
[x] ```Preview Mode Ctrl+P``` is not proper. It does not closes after opening and remains at its place. It must simply be a tootlip. 

> What did you expect to see that you didn't?
There must be a seperate scroll view in rich text editor too.

GIF for the same:
![Peek 2019-03-27 15-40](https://user-images.githubusercontent.com/32747809/55068454-e4ce5a00-50a7-11e9-94bd-85cecfef70f2.gif)

### Please show us where to look

https://publiclab.org/post

### What's your PublicLab.org username?

> This can help us diagnose the issue: 
divyabaid16

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by divyabaid16** [comment]
I would like to work on this!

**Comment by rexagod** [comment]
Great! Please do! 👍

**Comment by ebarry** [comment]
Thanks for working on this!

**Comment by VladimirMikulic** [comment]
@divyabaid16  Could you please tell us your OS and browser?
I've tested this on Chrome, Firefox and Edge there is no issue that you've specified.

[Demo](https://streamable.com/43bj6)

**Comment by divyabaid16** [comment]
Oh, I had it in Firefox and my OS was Linux mint.

**Comment by VladimirMikulic** [comment]
@divyabaid16 This seems to be fixed, could you close this issue?

**Comment by divyabaid16** [comment]
Ya, this issue is solved now. Thank you!!!
