### ISSUE TITLE
Formatting toolbar debugging

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/PublicLab.Editor#316]
# Description
In the get involved , post your work section, the toolbar in the 4th step doesn't work as required.
The last four buttons are ambiguous and don't open on click and A description of what the button does doesn't open up on hover.

![post](https://user-images.githubusercontent.com/32260628/54748850-da6c1600-4bf8-11e9-9e8a-9ab48b0d52f9.gif)

# Expected
If these buttons are of no use they can be removed else functionality needs to be added to them.

**Comment by jywarren** [comment]
Sorry it took me a while to transfer! Thank you!

**Comment by rexagod** [comment]
Those buttons do have some functionality associated with them. @ananyaarun Can you tell us the steps to reproduce this case and verify if this is still happening on your local? Thanks!

**Comment by ananyaarun** [comment]
@rexagod , i just checked again at http://localhost:3000/post as shown in my gif i still can't use the last 4 buttons and they don't have a pop up on hover explaining them as well.
Not sure why though !?

**Comment by keshav234156** [comment]
This issue is fixed now!!
