### ISSUE TITLE
Weekly Community Check-in # 16

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/PublicLab.Editor#317]
Hello Everyone!!!

We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal dart. You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check:

If you're new here, welcome :balloon: and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.
You can find them at 

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from last week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our Gitter chatroom :open_hands:

**Gitter**

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation page.

**This Week's Theme**

Check out issues at [https://code.publiclab.org/#r=all](https://code.publiclab.org/#r=all) and publiclab/plots2#4963 if you are a first-timer who is in search of an issue to start your open source journey. You are always welcome!

**Welcome new contributors**! This week, create at least 1 new ```first-timers-only``` (FTO) issue for welcoming a new contributor to Public Lab. The ideal FTO issue is one which:
- Follows FTO issue template - [https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md](https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md)
- Have all the relevant information that a beginner needs for understanding and solving the issue
- Have code-snippet required to solve the issue in case the change required is a bit complex

Last week a good number of ```FTO's``` were created [https://publiclab.org/notes/gauravano/03-29-2019/software-community-growth-through-first-timers-only-issues](https://publiclab.org/notes/gauravano/03-29-2019/software-community-growth-through-first-timers-only-issues) and it is very well written by @gauravano and we hope the same for this week too. It won't be possible without all your contributions :smile: 

**Google Summer of Code**
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best to get some ideas into the discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
[https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019](https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019)

And this is the official idea’s page:
[https://publiclab.org/wiki/gsoc-ideas](https://publiclab.org/wiki/gsoc-ideas)

The proposal can be submitted at [https://publiclab.org/notes/warren/02-28-2019/call-for-summer-of-code-2019-proposals](https://publiclab.org/notes/warren/02-28-2019/call-for-summer-of-code-2019-proposals) to get reviews from the mentors.

Along with this, our past GSoC members Vidit, Naman, and Sagarpreet gave this GSoC Webinar, where they explained the procedure of this program and explained their previous year proposals for Public Lab. Also explained their idea page for SoC programs as well.
[https://www.youtube.com/watch?v=BNhBd_WfKVA&t=618s](https://www.youtube.com/watch?v=BNhBd_WfKVA&t=618s).
This is amazing and would be helpful to all the GSoC aspirants!

cc
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @geekychaser @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @HarshKhandeparkar @aashna27 @Harshithpabbati @marieram @swiatek7 @kaunair
@niravasher

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment.

People who did the check-ins-

Sidharth Bansal (@SidharthBansal)
Cess (@cesswairimu )
Rishabh Rawat (@Rishabh570 )
Sasha Boginsky (@sashadev-sky)
Rishabh Kr Bothra (@geekychaser)
Shubham Sangamnerkar (@shubhscoder)
Siddhant N Trivedi(@sidntrivedi012)
Isha Gupta (@IshaGupta18)
Gaurav Sachdeva (@gauravano)
Harshith Pabbati (@Harshithpabbati)
Gaurav Sachdeva
Harshith Pabbati (@Harshithpabbati)
Harman Jolly (@CoderJolly )
Divya Baid (@divyabaid16)

Have a great week everyone :balloon: :tada: :sparkler:

**Comment by divyabaid16** [comment]
@marieram @swiatek7 @kaunair @gauravano @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps

@subhahu123 @An0u @Jaya738 @mgroovyank @shreyateeza @TANGL3SIT3S @nazeem1988 @karunagoyalk @Nirvikalpa108 @cassianoblonski @EngrEric @Anjalizi @GettyOrawo @coderbeetle @corbettbw @govindjeevan @gautamig54 @daddyjab @emestabillo @letnewKid @srujana121 @jazdao @ChinwenduSilvia @aggarwal19 @Jenniline @madelinejones @helenatxu @richa031 @fabsar @kuja24 @megha070 @Aarabhi2017 @Manvi07 @siddhishree @Julius26 @VinneyJ @sonali9696 @rarrunategu1 @coreytegeler @labseven @milomacphail @CleverFool77 @ananyaarun @ananya @divyabaid16 @publiclab-mimi @vaarigupta @alonpeer @madeofhuman

**Comment by divyabaid16** [comment]
Some newcomers: Welcome!!!
@shubhi2000 @Priyak5 @vaarigupta @techchic @ananya @hc-barker @edwd42 @PritiShaw @themonster2015 @supriya-kotturu @AnthoniaOkafor @jtmims @scheleon @mahmodHammad @santushk @jillpena @stoic-plus
@vaarigupta @alonpeer @madeofhuman

**Comment by gauravano** [comment]
@ibnjunaid @HarshKhandeparkar @aashna27 @Harshithpabbati @niravasher @mmmelissa

**Comment by gauravano** [comment]
Awesome check-in @divyabaid16 :100:

**Comment by sagarpreet-chadha** [comment]
Hey everyone ,
Anyone here with knowledge of Javascript and experience with Jasmine testing ?
If you are up for some tricky issue , do jump over to this PR : publiclab/leaflet-blurred-location-display#52 . Thank you :smiley: !

Any help is appreciated :raised_hands: .

**Comment by niravasher** [comment]
Good evening from Mumbai. This week I am about to finish writing my GSOC proposal.
Thank you and all the best to everyone

**Comment by sagarpreet-chadha** [comment]
Hey everyone ,

So i finally got myself unstuck 😄 from this tricky issue that i was facing for the last few weeks (https://github.com/publiclab/leaflet-blurred-location-display/pull/52) .

**Things i learned** : 
1.) Ask for help , sometimes other may give a different perspective on how to approach the problem 👍 
2.) Document how you got yourself unstuck so that others who may face this problem can solve it with ease . 
3.) Never lose hope !

Thanks everyone  💃  🎈 !

**Comment by niravasher** [comment]
@jywarren could you open some more issues to be solved in the ideas list for image-sequencer as some of them are already solved and some are referenced by others

**Comment by Rishabh570** [comment]
Hi everyone :wave:, hope everyone's doing great :smiley: 

Things I'll be doing:
- I'll be trying to create some more ftos this week :memo:
- I'll be updating my soc proposal a bit.


Great check-in @divyabaid16 :tada: Thanks!!!

**Comment by CoderJolly** [comment]
Hi everyone, Hope everyone's doing great 😃

* About to finish writing my soc proposals
* Would be solving some issues

Awesome check-in @divyabaid16  🙌

**Comment by sagarpreet-chadha** [comment]
Hi everyone ,
I have written this note 🗒  here introducing the new LBLD library 🗺 🔍  ! Do check it out everyone :) Thank you 😄  !
https://publiclab.org/notes/sagarpreet/04-02-2019/introducing-leaflet-blurred-location-display 🎉

**Comment by CleverFool77** [comment]
Hey everyone,
Hope an amazing week. :tada:
let's keep contributing and help out others.

**Comment by jywarren** [comment]
Hi everyone! Just noting -- Cloud9 is going to shut down our free accounts soon, and recommend switching to AWS Cloud9, which does not have that free tier. 😮 😢 

For starters, if you're actively using it, I recommend getting your data out! https://docs.c9.io/docs/migration-checklist

And you might try using (free) https://codenvy.io instead -- we've had some initial success with it in MapKnitter, and are interested to see if it's easy to get started on: https://github.com/publiclab/mapknitter/issues/408

Thanks!!!

**Comment by gauravano** [comment]
Hey everyone, 

> Hi, all, @SidharthBansal suggested some video chats from time to time -- maybe once per month? -- and i thought of the idea of themed code meetups - like discussing javascript testing, Rails unit testing, skylight/sentry error tracking, resolving codeclimate "smells", things like that, for topics people may find useful. I know that @cesswairimu and @StlMaris123 have done lots of in-person meetups on themes like these and wonder what they (and everyone else) thinks of this idea?

Approximately 3 weeks ago, @jywarren and @SidharthBansal put forward the idea of **Monthy Code Meetup** where we all can discuss different topics such as  javascript testing, Rails unit testing, skylight/sentry error tracking, resolving codeclimate "smells", etc. 

We are brainstorming about that idea and so want to know your opinion regarding the time of meetup, which time would be suitable for majority of you.

**Option 1:** https://everytimezone.com/s/4058efe0

**Option 2:** https://everytimezone.com/s/39c0f20a

/polls Option1 'Option 2' 

Thanks!

**Comment by CoderJolly** [comment]
> Hey everyone,
> 
> > Hi, all, @SidharthBansal suggested some video chats from time to time -- maybe once per month? -- and i thought of the idea of themed code meetups - like discussing javascript testing, Rails unit testing, skylight/sentry error tracking, resolving codeclimate "smells", things like that, for topics people may find useful. I know that @cesswairimu and @StlMaris123 have done lots of in-person meetups on themes like these and wonder what they (and everyone else) thinks of this idea?
> 
> Approximately 3 weeks ago, @jywarren and @SidharthBansal put forward the idea of **Monthy Code Meetup** where we all can discuss different topics such as javascript testing, Rails unit testing, skylight/sentry error tracking, resolving codeclimate "smells", etc.
> 
> We are brainstorming about that idea and so want to know your opinion regarding the time of meetup, which time would be suitable for majority of you.
> 
> **Option 1:** https://everytimezone.com/s/4058efe0 (👍 for choosing this)
> 
> **Option 2:** https://everytimezone.com/s/39c0f20a (❤️ for choosing this)
> 
> Thanks!

Its a great initiative, looking forward to it 🎉

**Comment by sashadev-sky** [comment]
@gauravano that is a genius alternative to polling 👍👍

**Comment by sashadev-sky** [comment]
Hi everyone!

This week I am: 
1) Working on the exporter system for Mapknitter
2) Fixing some toolbar bugs for Leaflet.DistortableImage
3) Helping to resolve issues on my currently opened FTOs

Thank you!

**Comment by cesswairimu** [comment]
Hello everyone,  

Finally got mapknitter working fine locally :tada: :tada:
This week I am solving bugs and writing functional tests in mapknitter.
Awesome checkin  @divyabaid16

Great rest of week all.

**Comment by jywarren** [comment]
Hi all! My day off was very worthwhile, i feel much better -- but now i'm a
bit behind on responding to PRs and reviewing proposals. Thanks for your
patience and it's especially amazing to come back and see so much activity
going so smoothly and people helping each other out even when I was
offline! I want to say THANK YOU especially big, but also to remind people
to take a break when you need one. I did! <3

**Comment by gauravano** [comment]
Anyone interested in opening the next check-in? Let's open next check-in at LEL. Thanks!

**Comment by gauravano** [comment]
Also, do add your reaction as per your time preference for the code meetup - https://github.com/publiclab/PublicLab.Editor/issues/317#issuecomment-479628410.

**Comment by gautamig54** [comment]
@gauravano I would like to open the next check-in. Kindly help me with the steps to be followed.
Thanks!

**Comment by gauravano** [comment]
Great! you can follow this -
https://github.com/publiclab/plots2/blob/master/doc/CHECKINS.md. Thanks!

**Comment by gauravano** [comment]
New check-in at https://github.com/publiclab/leaflet-environmental-layers/issues/164. Thanks @gautamig54!
