### ISSUE TITLE
Run eslint on `src/PublicLab.Builder.js` and remove all the errors for proper JS coding style

### ISSUE THREAD

**Issue by newbazz** [publiclab/PublicLab.Editor#337]

**Comment by newbazz** [comment]
@SidharthBansal @gauravano can someone tell me how to label these tasks?

**Comment by pydevsg** [comment]
@newbazz I can help you out in this, can you add a small description of this issue .
For adding label issue you should talk to @jywarren , @newbazz

**Comment by shreyaa-sharmaa** [comment]
Closing with #519
