### ISSUE TITLE
Run eslint on `src/PublicLab.Editor.js` and remove all the errors for proper JS coding style

### ISSUE THREAD

**Issue by newbazz** [publiclab/PublicLab.Editor#339]
You are requested to paste the screenshot of the errors shown on running eslint on the file.

**Comment by developer22-university** [comment]
OK @VladimirMikulic

**Comment by Shulammite-Aso** [comment]
Hello @developer22-university  are working on this?  If not can I work on it? @newbazz

**Comment by Shulammite-Aso** [comment]
if issue #338 is available and this one is not, I can as well work on that.
