### ISSUE TITLE
Toggling to rich text mode using shortcut key, disables the button

### ISSUE THREAD

**Issue by debck** [publiclab/PublicLab.Editor#341]
### Please describe the problem (or idea)

In the 3rd step, when we try to preview the Rich text using the shortcut key (`Ctrl+P`).  The preview button gets disabled and we cant move back to the markdown view.
It changes and starts working only if we refresh the page

### Screenshot reference 
* When we press `Ctrl+P` :  **output** - Button gets disabled

![Capture1312342344](https://user-images.githubusercontent.com/33368759/68617115-84801180-04ec-11ea-9342-9a2349af9726.PNG)

* When we refresh the page : **Output**- It gets corrected

![12dsf](https://user-images.githubusercontent.com/33368759/68617171-af6a6580-04ec-11ea-9cae-cefd3282398d.PNG)

### Please show us where to look

https://publiclab.github.io/PublicLab.Editor/examples/

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by debck** [comment]
@SidharthBansal  Can you please add the appropriate labels, as I don't have access to do so. 
And we can add to the GCI dashboard after that.

**Comment by rexagod** [comment]
Uploaded to GCI dashboard.

**Comment by SidharthBansal** [comment]
Published on GCI dashboard
