### ISSUE TITLE
Lat and lon in editor

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/PublicLab.Editor#342]
Integrating the simple editor URL into a prompt button attached to inline and
page-leading maps, which preserves the current map center as lat/lon
parameterss

**Comment by jywarren** [comment]
Hi Cess! I'm wondering if we can have this happen in the template for the
editor on plots2 - here?
https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb#L358
but
maybe it needs some ability to set the defaults through the editor options?

**Comment by cesswairimu** [comment]
Oh yeah that  would be doable... Will take a look and move the issue to plots2. Thanks

**Comment by jywarren** [comment]
I think this is complete in #353 and #349! awesome! 🙌
