### ISSUE TITLE
Integrate url with lat and lon params

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/PublicLab.Editor#348]
Integrating the simple editor URL into a prompt button attached to inline and
page-leading maps, which preserves the current map center as lat/lon
parameters

**Comment by jywarren** [comment]
Yeah! Well have to maybe be able to set the lat/lon defaults via a
constructor option! Let's find the spot in the code to do this. We can look
at other modules for an example!

**Comment by jywarren** [comment]
I think this is complete in #353 and #349! awesome! 🙌
