### ISSUE TITLE
Integrate autocompletion code into plots2 codebase

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#365]
After #55, we should circle back and start using the autocompletion code in `plots2`!

https://github.com/publiclab/PublicLab.Editor/blob/7b8a5f82149b88a52ee60ae516212917d23df723/examples/data/atwho.PLE.js

https://github.com/publiclab/plots2/ would need to have that JS file included, and then https://github.com/publiclab/PublicLab.Editor#atwhojs-data-module instructions followed. We'd love help with this after #55 is complete!

**Comment by niravasher** [comment]
Shouldn't this issue be opened in plots2 and then copy the file there? @jywarren

**Comment by keshav234156** [comment]
@niravasher I am already working on this . We actually need to follow  the instruction mentioned https://github.com/publiclab/PublicLab.Editor#atwhojs-data-module but it didn't integrate it.I will open a PR soon and lets collaborate on it

**Comment by niravasher** [comment]
Tell me how can I contribute here @keshav234156 ?
