### ISSUE TITLE
Update map instructions privacy link

### ISSUE THREAD

**Issue by nstjean** [publiclab/PublicLab.Editor#366]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [PublicLab.MapModule.js](https://github.com/publiclab/PublicLab.Editor/blob/master/src/modules/PublicLab.MapModule.js) in the `PublicLab.Editor` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Currently this is the code for the map instructions on line 16:
https://github.com/publiclab/PublicLab.Editor/blob/7b8a5f82149b88a52ee60ae516212917d23df723/src/modules/PublicLab.MapModule.js#L16

We need to change it to the following:
```
    _module.options.instructions = 'Add a map to your note. Learn about <a href="https://publiclab.org/location-privacy" target="_blank">location privacy here »</a>' ;
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
@SidharthBansal This can also be added to GCI dashboard.

**Comment by anshukaira** [comment]
hi. I am an outreachy applicant! can i please work on this issue. also this is my first time contributing like this.

**Comment by anshukaira** [comment]
https://github.com/publiclab/PublicLab.Editor/pull/413
I do not know what to do next.. and i do not even know that what I did just now was right or there is another way of doing it.
Someone?? Please help

**Comment by anshukaira** [comment]
@nstjean ?? @VladimirMikulic ...sorry but a little help here

**Comment by Shulammite-Aso** [comment]
@anshukaira I think the instruction was to line 16 of this file https://github.com/publiclab/PublicLab.Editor/blob/7b8a5f82149b88a52ee60ae516212917d23df723/src/modules/PublicLab.MapModule.js#L16 to this 👉_module.options.instructions = 'Add a map to your note. Learn about <a href="https://publiclab.org/location-privacy" target="_blank">location privacy here »</a>' ;

**Comment by Shulammite-Aso** [comment]
@nstjean I would also like to work on this issue. 
If @anshukaira Would get assigned this issue then can you  point me to some other issue that is suitable for a first time contributor?

I'm also an outreachy applicant and looking to make my first contribution to this project.

**Comment by Shulammite-Aso** [comment]
I'm also open to working on issues that may be more than one line of code, only I would appreciate the extra guidance that comes with FTO issues.

**Comment by nstjean** [comment]
@Shulammite-Aso I will take a look at what else is available for you!
