### ISSUE TITLE
Map covers Publish button

### ISSUE THREAD

**Issue by nstjean** [publiclab/PublicLab.Editor#367]
I noticed that when you scroll up and down the map on the screen completely covers the footer including the `Publish` button. We need to fix it so the map goes underneath that footer section! :smiley: 

![FireShot Capture 112 - PublicLab Editor - ](https://user-images.githubusercontent.com/49460529/70823706-933d3b00-1dae-11ea-8be8-73049926e6bc.png)

**Comment by nstjean** [comment]
@SidharthBansal

**Comment by nstjean** [comment]
@SidharthBansal has this been added to GCI dashboard?

**Comment by jywarren** [comment]
I think this is a z-index issue in CSS, if it's helpful!

**Comment by vaibhavmatta** [comment]
Hey @nstjean , @jywarren , @SidharthBansal Is this issue resolved? If not, then I want to claim this issue. Thanks! 😊

**Comment by nstjean** [comment]
It looks like it was completed but not merged! Thanks for the note, I'll get someone to merge #392 . @cesswairimu do you have access to merge on this repository?

**Comment by cesswairimu** [comment]
checking..

**Comment by cesswairimu** [comment]
Nope I do not have merge rights.. pinging @emilyashley or @SidharthBansal
