### ISSUE TITLE
Unable to publish new content 

### ISSUE THREAD

**Issue by rajcrk** [publiclab/PublicLab.Editor#369]
### When trying to publish new content, the server returned with an error response of status code 405.

> steps to reproduce.

- visit the link https://publiclab.github.io/PublicLab.Editor/examples/
- Fill in your awesome content you wanna fake publish.
- Click Publish button at the bottom

![Screenshot from 2019-12-17 15-51-12__01](https://user-images.githubusercontent.com/15966586/70987516-0ebc2680-20e6-11ea-82ab-679ee780d8a9.png)

### Chrome, version: 78.0.3904.87 , and Ubuntu 16.04

****

**Comment by jywarren** [comment]
Hi! That's because the link you used is a demo only! This library is embedded in the PublicLab.org website at https://publiclab.org/post however. Does that make sense? Thanks!
