### ISSUE TITLE
Number of steps left doesn't show correctly

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/PublicLab.Editor#37]
I see a little problem in the No of steps left displayed in the bottom right corner of the editor. It shows just fine when you fill out the body first and then the title. But if you fill out the title first and then the body (which is the usual order of posting a note) it shows `1 of 2 steps left`. Also the Submit button is disabled until then so basically you can't post despite filling out all the title and body. Only after you write something in the title again all steps are shown to be complete and the Submit button is enabled.

**Comment by jywarren** [comment]
This should actually be called "X /required/ steps left" -- but we don't
have enough space in the interface for that. But I haven't come up with a
good design solution for this problem, so I'm considering simply removing
that feature?

What if we displayed "0/4" but on hover, it says "0 of 4 required steps
remaining"?

**Comment by ananyo2012** [comment]
Yes that can work but I really like the disable feature of the Submit button which doesn't enable until all the required fields are filled. Though it is little buggy now. I saw the button once enabled remains as it is. It would be great that it would be disabled until all required fields are filled up.

**Comment by jywarren** [comment]
I think we can keep that, and also show a tooltip that says "2 of 3
required steps remaining" over the button, no?

**Comment by ananyo2012** [comment]
Yes this sounds best!

**Comment by jywarren** [comment]
ah, hmm. So perhaps we should refresh the state of the button on each
"validate" action?

**Comment by gauravano** [comment]
Hey @jywarren, the detailed issue is reported about the problem which I commented above 
> Current status: number of steps remain/required shown correctly but submit button enabled once both steps are completed. What if user deletes the body then submit button should be disabled but it does'nt.

Issue about this problem at #250. Do you think we can close this issue @jywarren? 

Thanks!

**Comment by jywarren** [comment]
Yes I think so. Thanks!
