### ISSUE TITLE
Coordinates are not rounded to correct precision

### ISSUE THREAD

**Issue by nstjean** [publiclab/PublicLab.Editor#375]
I noticed today that in the `examples/index.html` file the map coordinates are showing 6 decimal points and are not rounded to the correct precision. It stays that way when I scroll and zoom in and out.

![FireShot Capture 126 - PublicLab Editor - ](https://user-images.githubusercontent.com/49460529/71263820-b1f08400-2310-11ea-90ad-e184e8f9dee2.png)

I suspect my code changes are to blame, I will try to fix this later today!

**Comment by nstjean** [comment]
Ooops! Nevermind! blurredlocation was not checked, and that's why. I've been staring at blurred coordinates too long. :blush:

**Comment by jywarren** [comment]
:-) I think there should be a test for this, so we shouldn't have to be too
worried? But I'm not sure. Thanks!
