### ISSUE TITLE
Error message doesn't show correctly for unsuccessful Submission

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/PublicLab.Editor#38]
If the form Submission fails due to some reason such as not entering the title or body (or if any validation check fails at database side) the entire html template is appended to the url as response text and no appropriate error message is displayed. This is what I am getting for a unsuccessful submission while integrating it with a Rails server(Testing with the plots code).
![error_editor](https://cloud.githubusercontent.com/assets/10486343/17731681/fa0d823e-648b-11e6-9a8a-53f52edf67c7.png)

**Comment by jywarren** [comment]
Ooh, that's no good. But I believe this should be filed under the
publiclab/plots2 repository, not in the editor. Thanks for catching that,
it's a big deal! Post-submission error handling is not something I'd
thought through, and maybe we need a way to pass errors into the interface,
to display red lines and error messages around incorrect fields?

**Comment by ananyo2012** [comment]
Yes we can write some javascript to show some error messages around incorrect fields according to the response text. Though we can easily do this through rails error messages but I thought it would be great that we did it through parsing the response text then it would be much generic and would work for any framework and since the submit is a javascript submit. So I thought of filing this issue here.

**Comment by jywarren** [comment]
Ah, i see -- yes, let's make a new issue called "error display system using
response JSON" or something? And reference the Bootstrap styles here:
http://getbootstrap.com/css/#forms-control-validation

**Comment by jywarren** [comment]
Error display via Rails is working -- the above error was due to an overlarge form submission, however, which is not a validation error but a more serious one -- but I also switched the form submission to POST instead of GET. So, closing on both counts!
