### ISSUE TITLE
Stickness of toolbar

### ISSUE THREAD

**Issue by keshav234156** [publiclab/PublicLab.Editor#394]
![Screenshot from 2020-02-01 20-17-37](https://user-images.githubusercontent.com/45951376/73594011-1c136000-4530-11ea-9e0d-834ab201912f.png)

![Screenshot from 2020-02-01 20-36-03](https://user-images.githubusercontent.com/45951376/73594231-7f9e8d00-4532-11ea-9bcd-281b3c7d24b8.png)

As you can see the toolbar always remains sticked to the bottom. Is it a bug or intended behavior.
It's caused by this piece of code 
https://github.com/publiclab/PublicLab.Editor/blob/7aacb32e7bdb5e3aa72e3ba61311a7fbc442b759/src/modules/PublicLab.RichTextModule.js#L311-L335

**Comment by keshav234156** [comment]
@emilyashley  @jywarren @VladimirMikulic Would love your inputs here?

**Comment by VladimirMikulic** [comment]
@keshav234156 I agree with you. This was strange to me also. In my opinion, the toolbar shouldn't be sticky.

**Comment by jywarren** [comment]
Just want to note the great discussion by @Shulammite-Aso and others here:

> Okay @keshav234156
> Also wondering what you intend to with #394 ? i was looking at how the formatting bar is positioned in some other editors and i found some two positioning styles we could possibly consider.
> On [wordpress.com](https://wordpress.com/) and on https://wordpress.org/gutenberg/ the formatting bar appears where your cursor is at the moment.
> 
> ![WPformating](https://user-images.githubusercontent.com/48386390/82989444-41017680-9fea-11ea-861f-078b65944743.gif)
> 
> while on https://froala.com/wysiwyg-editor/ the bar stays fixed at the top of the editor text area.
> 
> ![floraFrmating](https://user-images.githubusercontent.com/48386390/82989732-a8b7c180-9fea-11ea-8802-19ee9730c749.gif)
> 
> I was thinking of trying to implement that of making it stay fixed at the top like in the second gif, as i think it may be easier to implement than that of wordpress.

And, I think it's good to read through previous discussions also to see how we got here, and if we're undoing or redoing things from past discussions. Here are some issues which mention the toolbar!

* #404 and original one with discussion here: https://github.com/publiclab/plots2/issues/7518
* https://github.com/publiclab/PublicLab.Editor/issues/308
* minor fix in https://github.com/publiclab/PublicLab.Editor/issues/228
* the original issue! https://github.com/publiclab/PublicLab.Editor/issues/127

Let's see. I think the various cases people are trying to deal with are:

1. Original feedback from #127: `The formatting bar stays at the bottom of long notes so you have to scroll all the way down to the bottom to use it. If you are doing repeated formatting it can get tedious to highlight the text, scroll down, click the button, scroll up, highlight the text, scroll down etc.` (i.e. putting it at the bottom means it is closest to where you are when you're writing the post)
2. but with it at the bottom, now it's hard when you want to edit the top of a long post
3. so floating allows it to be at a convenient place no matter where you are, but has downsides too (what are they? Let's list them!)
4. one last issue - unlike editing in a GitHub comment, the textarea doesn't scroll out of view, allowing the formatting bar to remain visible (see screenshot below)
5. are there other ways to do this? 

![image](https://user-images.githubusercontent.com/24359/83563706-8261bc80-a4e9-11ea-9256-952186951fdc.png)

Any other cases or observations? Let's get a full understanding and then figure out what's best! I also LOVE the idea of closely following norms from a widely used system like Gmail or something, to @Shulammite-Aso's suggestions. 

And, finally, perhaps the post on "how people use the editor" is a good place to ask for user feedback on things like this!!! https://publiclab.org/questions/emash/06-01-2020/how-do-you-write-and-post-in-the-public-lab-community-asking-for-our-developers

Thank you all!!!

**Comment by Shulammite-Aso** [comment]
This is great info!! I have seen a few of these discussions before. and the primary goal is to have the toolbar become easily accessible to people making posts n the editor (especially long posts).  personally i think the method we have in place now, i.e having it float around does solve the problem, only it becomes a bit distracting because it also floats pass the text area.

i've made a PR that fixes the floating outside the text area, but still leaves it positioned at the bottom.  We could have it at the top, but maybe we should let  other users say their thought on that.
Also the popup toolbar can very much work too, only it may also need to make the toolbar shorter and maybe add a  "more" icon to access the rest of the tools.

> And, finally, perhaps the post on "how people use the editor" is a good place to ask for user feedback on things like this!!! https://publiclab.org/questions/emash/06-01-2020/how-do-you-write-and-post-in-the-public-lab-community-asking-for-our-developers
> 
Also about this part, sounds like a good idea. Maybe i could add that as a comment on the question, as i don't think i can edit it t add a toolbar specific query?

**Comment by emilyashley** [comment]
Yes please feel free to add additional questions on that community question! :)
