### ISSUE TITLE
Save as Draft

### ISSUE THREAD

**Issue by keshav234156** [publiclab/PublicLab.Editor#397]
We previously had a "save as draft" option. Was it removed recently?

**Comment by keshav234156** [comment]
@VladimirMikulic @emilyashley @jywarren

**Comment by VladimirMikulic** [comment]
We have it on plots2, but not on this repo. It's likely dynamically injected in plots2.

**Comment by keshav234156** [comment]
@VladimirMikulic I can see the option at https://publiclab.org/post

**Comment by VladimirMikulic** [comment]
Exactly.

**Comment by keshav234156** [comment]
@SidharthBansal Why was this closed? Is the option present?

**Comment by VladimirMikulic** [comment]
@keshav234156 yes it is.

**Comment by keshav234156** [comment]
@VladimirMikulic Can you please provide a screenshot where it is present

**Comment by VladimirMikulic** [comment]
Just like you said, it is present on pl.org/post.

**Comment by keshav234156** [comment]
@VladimirMikulic Sorry for wrong comment I meant I can't see the option on https://publiclab.org/post

**Comment by keshav234156** [comment]
![Screenshot from 2020-02-05 00-18-15](https://user-images.githubusercontent.com/45951376/73776015-065e9e80-47ad-11ea-843c-4ee654e8efc4.png)

**Comment by SidharthBansal** [comment]
Yes option is present. I was making a tea so there was delay in reply.

**Comment by keshav234156** [comment]
Where?

**Comment by VladimirMikulic** [comment]
The PL website has been updated, you might have been running the old version.
Here is the screenshot.

![Screenshot_20200204_195121](https://user-images.githubusercontent.com/35997844/73776313-d0f38a00-4787-11ea-8c3f-05dad06323eb.png)

**Comment by keshav234156** [comment]
@VladimirMikulic why it not present in my screenshot.It's very strange.

**Comment by VladimirMikulic** [comment]
Try clearing cache :)

**Comment by keshav234156** [comment]
no.It's still not present.Can you please clear your cache once.

**Comment by VladimirMikulic** [comment]
I am running the latest version and even after clearing the cache the option is present.
