### ISSUE TITLE
Lock floating toolbar for formating in public lab posts 

### ISSUE THREAD

**Issue by imajit** [publiclab/PublicLab.Editor#404]
This is a issue related to [plots2 issue](https://github.com/publiclab/plots2/issues/7518). 
Issue to solve
- lock floating toolbar to only text region
- format style of last 4 buttons in toolbar
I'm currently working on the issue

**Comment by keshav234156** [comment]
@imajit Thanks for showing up your interest regarding this!!.But PR for this is already opened https://github.com/publiclab/PublicLab.Editor/pull/395  and https://github.com/publiclab/plots2/issues/7532 .
