### ISSUE TITLE
Popup not disappearing 

### ISSUE THREAD

**Issue by imajit** [publiclab/PublicLab.Editor#407]
the tool-tip for inserting table and some other tool-tips do not disappear on clicking somewhere else on screen and only disappear only when clicked on a specific button like in case of table we need to click the table button again to hide the tool-tip.
![Screenshot from 2020-02-24 03-00-10](https://user-images.githubusercontent.com/38528640/75120418-d884bf80-56b1-11ea-8d1f-ba5098b155b7.png)
I have seen similar issue like this in plots2 repo but not sure if they are related to this or not

**Comment by Kirti2502** [comment]
Hi, I am an outreachy applicant and I would like to take up this issue.

**Comment by nstjean** [comment]
@Kirti2502 Sure! We just ask that you take one issue at a time. So you can choose which one of the issues here to start with, just post a comment claiming that issue so everyone knows you are working on it. :) Welcome!!!

**Comment by Kirti2502** [comment]
Sure, I will take care of this from next time.

**Comment by nstjean** [comment]
Great! Let us know if you have any problems! :smile:

**Comment by Kirti2502** [comment]
Hi! I've tried adding data-trigger=focus element to the popover to make it dismissible but that does not help. Can I get some help to know what could be wrong.
Thank you.

**Comment by Kirti2502** [comment]
I have opened a pull request please review.
Thank you.

**Comment by NitinBhasneria** [comment]
@Kirti2502 If you have opened any pr for this issue please describe this issue in the pr as
Fix #407
Ask is tuck in any problem.
thanks

**Comment by keshav234156** [comment]
@Kirti2502 are you still working on this?

**Comment by NitinBhasneria** [comment]
looks like this issue will be solved in jywarren/woofmark repo. @VladimirMikulic am I right? 
Just confused because I can't see the table insertion in jywarren/woofmark.

**Comment by NitinBhasneria** [comment]
Fixed in https://github.com/jywarren/woofmark/pull/3.
