### ISSUE TITLE
Issue in navbar

### ISSUE THREAD

**Issue by govindgoel** [publiclab/PublicLab.Editor#411]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
The topics section pop up but does not close when you click anywhere on the page
After clicking on tools section if you hover over community section it it overlaps and vice-versa.

![ ](https://media.giphy.com/media/Xzdg0cVS5YmkrIbBUh/giphy.gif)

### Please show us where to look

https://publiclab.org/ post

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Kirti2502** [comment]
Hi, I am an outreachy applicant and I would like to take up this issue.

**Comment by nstjean** [comment]
@govindgoel Do you think there is some code specific in PublicLab.Editor that is causing this behavior?

**Comment by govindgoel** [comment]
@nstjean  I will surely look into this as I was busy with some other work so I was unable to look into it.

**Comment by shreyaa-s** [comment]
@nstjean I have a potential fix for this. This can be fixed with simple JS. But this is not an issue of Editor but of the navbar in the website itself. I would like to fix it if it's available.

**Comment by nstjean** [comment]
@shreyaa-s Yes go ahead in [plots2](https://github.com/publiclab/plots2/issues)

**Comment by NitinBhasneria** [comment]
@nstjean @shreyaa-s This issue is already opened in plots2. 
@cesswairimu @govindgoel I think it should be closed here.
Thanks

**Comment by shreyaa-s** [comment]
@NitinBhasneria if possible, can you please mention the issue number or provide the link? I'm having trouble finding it. Thanks!

**Comment by govindgoel** [comment]
https://github.com/publiclab/plots2/issues/7593 
I didn't check it though that I already opened this issue in plots2.
