### ISSUE TITLE
Editor buttons sticks at wrong places.

### ISSUE THREAD

**Issue by Shulammite-Aso** [publiclab/PublicLab.Editor#418]
This is one of the issues identified in #302 no 3 particularly.

what i found happens here is, when on the editor body the position of the buttons div is set to relative:
![Screenshot from 2020-03-12 15-15-55](https://user-images.githubusercontent.com/48386390/76537293-78459a00-6475-11ea-81fe-96c13c079ee3.png)

but as you scroll away from the body the position becomes fixed, causing it to stick a you scroll whether up or down on the page, like is in the picture:
![Screenshot from 2020-03-12 15-26-07](https://user-images.githubusercontent.com/48386390/76537856-46810300-6476-11ea-8ffd-fb3e001aab76.png)

if there i a way to either hide or return the position of this div to relative after a user has scrolled passed the text area, the output would be better, as the user will only see the buttons when they're in the body text area and not when on the footer or any other place.

**Comment by Shulammite-Aso** [comment]
I don't know exactly were to find the code that is causing this behavior as i'm just getting to learn the codebase. 
@gauravano @jywarren if you can help with where one can look to find where this  issue is possibly coming from, you can please talk about it.

**Comment by keshav234156** [comment]
duplicate of  #394

**Comment by keshav234156** [comment]
@Shulammite-Aso can we close this issue?

**Comment by Shulammite-Aso** [comment]
Oh. it's the same i think.

And i had even seen that issue before, but it's either i didn't quite understand the issue at the time or i just didn't remember there was already an issue like that.

I should close this one now then.
