### ISSUE TITLE
An image can't be removed once it has been uploaded in the main image module

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/PublicLab.Editor#429]
In the Main Image module, there is requirement of Remove Image. As there is no way to remove the image once selected.

**Comment by NitinBhasneria** [comment]
@cesswairimu @emilyashley @nstjean @VladimirMikulic Kindly lookout. Thanks

**Comment by VladimirMikulic** [comment]
You are referring to the rich text mode, right?

**Comment by NitinBhasneria** [comment]
Yes.

> You are referring to the rich text mode, right?

**Comment by VladimirMikulic** [comment]
@NitinBhasneria then I don't understand what is the issue here.
You can simply click cancel on the modal and it won't insert the image.

**Comment by NitinBhasneria** [comment]
No, Actually I am talking about after inserting an image. Suppose we have inserted the image and then we decide to remove it. @VladimirMikulic

**Comment by VladimirMikulic** [comment]
I get it now. Currently, we don't have that feature. Good catch.

**Comment by NitinBhasneria** [comment]
Ok, thanks will be working on this.

**Comment by cesswairimu** [comment]
@crisner @nstjean what you think?

**Comment by nstjean** [comment]
I think there should always be a way to remove an image! Good catch.

**Comment by NitinBhasneria** [comment]
Fixed in #429. closing.
