### ISSUE TITLE
Data embedding Error in Editor

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/PublicLab.Editor#430]
If we copy-paste any table from other resources it will be pasted as it is but when the post is published the alignment of the table disturbs and it is not formatted as seen in the editor.

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @cesswairimu @nstjean @emilyashley Review this.

**Comment by VladimirMikulic** [comment]
@NitinBhasneria this should be posted to `plots2`. `plots2` renders posts. The editor doesn't have anything to do with it.

**Comment by NitinBhasneria** [comment]
@VladimirMikulic I think the editor cant have the exact format which we are copying in it.
What do you think?

**Comment by VladimirMikulic** [comment]
It's complicated, woofmark parses it and then the parsed HTML is sent to the server which later displays it. Probably Bootstrap classes and styles collide with the woofmark styles, but I am not sure though.

**Comment by NitinBhasneria** [comment]
Ok, @VladimirMikulic I will look at it. Thanks
