### ISSUE TITLE
Main Image Module pop up error

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/PublicLab.Editor#431]
When the image is uploaded the image popup shows the image. Here the problem is the text "Drag an image here to upload" is not disappearing it rather overlaps. 
![gsoc11](https://user-images.githubusercontent.com/44112080/77655603-a1e3e280-6f98-11ea-840b-2dbd72f211ae.png)

If we want to show the text we can show the text below the image as it looks weird when it overlaps with the image.
Thanks

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @cesswairimu @nstjean @jywarren have a look!

**Comment by VladimirMikulic** [comment]
Could be improved, definitely :+1:

**Comment by NitinBhasneria** [comment]
Thanks will be working on this then.
