### ISSUE TITLE
Choose file button extension

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/PublicLab.Editor#433]
In the main image module, after the choose file button er have a text before choosing any file "No file chosen". Here the problem is that the text is also included in the button. 

This text should be removed from the button.

![Screenshot from 2020-03-26 20-09-35](https://user-images.githubusercontent.com/44112080/77659178-ba0a3080-6f9d-11ea-9d0d-78a114f7dbc6.png)

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @jywarren have a look at this.
Thanks

**Comment by VladimirMikulic** [comment]
:+1:

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @cesswairimu Need some guidance for the "Choose File button".
Is it necessary to show the image name after uploading.

**Comment by VladimirMikulic** [comment]
It would be a nice UX :)
