### ISSUE TITLE
Error while uploading image

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/PublicLab.Editor#438]
When we upload image from the computer in example/index.html we encounter this error.

![editor2](https://user-images.githubusercontent.com/44112080/77824456-c242a700-7128-11ea-8643-2f7d86d759a3.gif)
![Screenshot from 2020-03-28 19-17-31](https://user-images.githubusercontent.com/44112080/77824459-ca9ae200-7128-11ea-9e05-ba526a77f6bf.png)

**Comment by NitinBhasneria** [comment]
please have a look @VladimirMikulic

**Comment by VladimirMikulic** [comment]
Please read the README file. You need `plots2` repo as well in order to run Editor locally (test image uploads which require a server).

**Comment by NitinBhasneria** [comment]
oh sorry will do so
