### ISSUE TITLE
Check that location sharing is enabled by user before posting it

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#444]
> What did you expect to see that you didn't?

The editor at https://publiclab.org/post (and https://stable.publiclab.org/post) will share location even if it has not been permitted by the user with the `Add a location` button:

![image](https://user-images.githubusercontent.com/24359/78048358-9c471d80-7347-11ea-89c3-e8e173292711.png)

Upon pressing `Publish`, the location data is copied into the tags field and submitted. 

![image](https://user-images.githubusercontent.com/24359/78048267-7883d780-7347-11ea-9d39-045d0953e6bf.png)

i believe we need to add an extra check in the editor publish routine that clears the location in JS if the location adding interface is not open

We could do that [here](https://github.com/publiclab/plots2/blob/295e2b23fbba1a24ff34a98b48e043de78f6c713/app/views/editor/rich.html.erb#L454-L460), by stripping the location out of the form if the location section is not open, but actually we want it to be preserved if you change your mind and open it. 

That is, the profile location should persist there, it just shouldn't be published unless that section is open.

**Comment by jywarren** [comment]
Indeed - here, it checks if the map element is hidden:

https://github.com/publiclab/PublicLab.Editor/blob/baf51ac431b2bab72042a8b612e0efce3fedddc8/src/PublicLab.Editor.js#L102-L109

I confirmed that this does tell you if the toggle is open, in the JS console. Odd!

**Comment by jywarren** [comment]
That's odd. on second test, it did respect my toggling. But i had hit the back button to get back to that page. I'll try doing it one more time from a fresh editor page.

**Comment by jywarren** [comment]
Third test from fresh editor on stable - it respected the toggle. Hmm.

**Comment by Shulammite-Aso** [comment]
Does this error still occur? it seemed to have worked fine in your last two test. 

I'm trying to reproduce this bug, but i don't know how to without publishing my post. But i've also confirmed that it performs the check

**Comment by NitinBhasneria** [comment]
@jywarren do you mean that the location should not be by default shown.

**Comment by jywarren** [comment]
@Shulammite-Aso i am not sure... i think we need to test more thoroughly. I didn't change anything between my tests so it seems it may just be a narrower bug but not gone. You can try it out on https://stable.publiclab.org, our testing server, and i believe it'll be the same username/pwd combo?

@NitinBhasneria if you've clicked `Remove location` here, then it should NOT share your location:

![image](https://user-images.githubusercontent.com/24359/79274591-cc77db80-7e72-11ea-9dce-bd574b45edb2.png)

However, it's OK if the location is preloaded there when you open the page. It's supposed to use the location from your profile to "guess" but to respect if you then decide not to attach it. 

Thanks, all!

**Comment by Shulammite-Aso** [comment]
Okay! I'll try to look more into this.

**Comment by NitinBhasneria** [comment]
@Shulammite-Aso Any update here?

**Comment by Shulammite-Aso** [comment]
None for now. I was not able to reproduce the bug the last couple of times I tried.

Have you tried reproducing it?

**Comment by NitinBhasneria** [comment]
No, I just wanted to know the updates before starting 😅😅. Thank you

**Comment by Sagarpreet** [comment]
Hey @jywarren 
The toggle is getting respected and the code verifies the same. 
However the issue seems to be different here: 
1. When we publish the post with location, and then we edit it -> Then map is not shown (tried in local) by default, also if you will remove the location tags now and hit publish then tags are still persisted.
2. Only way to remove location tags is clicking cross button on tags in post right bar.

**Comment by jywarren** [comment]
I think this is sufficient, thank you for tracing it though!!!
