### ISSUE TITLE
Scrolling restricted after image upload using browse option

### ISSUE THREAD

**Issue by shreyaa-s** [publiclab/PublicLab.Editor#445]
### Please describe the problem (or idea)
The code breaks if the user uses `browse` to enter images but works fine for `drag and drop`.

> What happened just before the problem occurred?
When an image is entered using `browse` the code breaks but not with `drag and drop`.
The scrolling gets restricted. Despite the attempts to scroll up or down, the pointer and focus move back to the image entered.
Once this happens the issue persists with scrolling even after the image is deleted.

### Please show us where to look

https://publiclab.org/post

A video representation of the same: 
https://drive.google.com/file/d/1JehUreFvpVAMYR03kFTfNtzoOxwKa9ig/view?usp=sharing

****

Thank you!

**Comment by NitinBhasneria** [comment]
Please upload a GIF of the issue @shreyaa-s.
Thanks

**Comment by shreyaa-s** [comment]
@NitinBhasneria I tried but it always ends up exceeding the size limit and I have yet to find any efficient gif compressor.

**Comment by NitinBhasneria** [comment]
![editor image](https://user-images.githubusercontent.com/44112080/78279573-5a7bca00-7535-11ea-93ec-6836bd918955.png)
![editor5](https://user-images.githubusercontent.com/44112080/78279690-8e56ef80-7535-11ea-82ac-efaa5790c696.gif)
@shreyaa-s does this describes your probelm?

**Comment by NitinBhasneria** [comment]
Also, I want you to know that the scrolling is genuinely off. Thanks

**Comment by shreyaa-s** [comment]
![simplescreenrecorder-2020-04-02_23 30 56](https://user-images.githubusercontent.com/55884943/78283840-0de7bd00-753c-11ea-8224-8977218a2588.gif)
@NitinBhasneria this is what I'm talking about. I can't scroll up or down once entering an image using `browse` but I can with `drag and drop`. I'm not sure if it's localized or a genuine bug. It would be great if you could try to reproduce it and confirm. Thanks for your input it's highly appreciated.

**Comment by shreyaa-s** [comment]
Also the scrolling problem persists even after removing the image.

**Comment by NitinBhasneria** [comment]
Ok. I got it thanks for the great catch. I will update you shortly. Thanks

**Comment by NitinBhasneria** [comment]
Ok, I checked the error. Actually, you are checking on publiclab.org/posts, but the updated version of the editor is on PublicLab.Editor please check from there. This error is removed already thanks.
In case you need any help, feel free to ask. thanks.

**Comment by shreyaa-s** [comment]
@NitinBhasneria  I checked but the problem persits. If you can't reproduce it then the bug might be localized. Waiting on further confirmation. Thanks!

**Comment by NitinBhasneria** [comment]
Ok, @shreyaa-s I cant see the scrolling resistance after image uploading. Scrolling is restricted when we click on image attachment and insert box appears. This needs to be fixed.Thanks

**Comment by shreyaa-s** [comment]
I don't think that's a bug. With a pop up in the forground there need not be scrolling in the background.

**Comment by shreyaa-s** [comment]
@NitinBhasneria  since you can't reproduce the error, it might be localized. Closing this issue.

**Comment by jywarren** [comment]
Thanks for digging into this folks! ❤️
