### ISSUE TITLE
Image placeholder line persists after uploading image

### ISSUE THREAD

**Issue by shreyaa-s** [publiclab/PublicLab.Editor#447]
### Please describe the problem (or idea)

Ideally I believe that the tag line used `Drag an image to upload` should not be visible after uploading an image.
![Screenshot_20200402_131652](https://user-images.githubusercontent.com/55884943/78238645-7150fb00-74fa-11ea-8e10-32c052673283.png)
Thanks!

**Comment by NitinBhasneria** [comment]
This issue is already fixed in #437. Please have a look and close this issue. Thanks

**Comment by shreyaa-s** [comment]
@NitinBhasneria thanks for mentioning it.

**Comment by jywarren** [comment]
Thanks, all!!! ❤️
