### ISSUE TITLE
Write help page for images, attach link from sidebar

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#45]
at https://publiclab.org/wiki/authoring-help#Images

**Comment by niravasher** [comment]
Hello @jywarren , could you please describe this issue in a bit detail?

**Comment by niravasher** [comment]
Hello @jywarren , could you please describe this issue in a bit detail?

**Comment by gauravano** [comment]
Hi @niravasher, this issue was about writing the Images section at  https://publiclab.org/wiki/authoring-help but I just visited the link and it's added now. Thanks to whoever added that section. Closing this now. @jywarren
