### ISSUE TITLE
Use location spinner error

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/PublicLab.Editor#451]
When you click on the Use location button under Map Module, the permission box appears. If you allow it the spinner disappears but on blocking the spinner is still there and does not disappear.
![editor6](https://user-images.githubusercontent.com/44112080/78292667-05e04b00-7545-11ea-8e14-684017dc9d47.gif)

**Comment by NitinBhasneria** [comment]
I got the error.
Actually error is in leaflet blurred location repo. I have attached a screenshot, also you can check on 
https://publiclab.github.io/leaflet-blurred-location/examples/
@VladimirMikulic @jywarren will it be ok to make changes in leafletBlurredLocation repo.
Thanks.
![Screenshot from 2020-05-30 18-00-42](https://user-images.githubusercontent.com/44112080/83328319-c95c7180-a29f-11ea-95cd-614f30107337.png)

**Comment by VladimirMikulic** [comment]
@NitinBhasneria that's correct. You need to make a change in the Leaflet Blurred Location repo.
Take a look at the changes in the last commit that I made. It should be easy to fix this issue.

**Comment by NitinBhasneria** [comment]
hey, @VladimirMikulic it looks like the problem is solved by the last commit. Although it is not reflected in https://publiclab.github.io/leaflet-blurred-location/examples/ and so not reflected in publicLabEditor.
So, I think this issue is solved. Thanks. @jywarren @keshav234156 @shreyaa-s @Shulammite-Aso please have a look and tell if still, you find some bug is there.
![editor2](https://user-images.githubusercontent.com/44112080/83367792-f01bc480-a3d3-11ea-8625-c129011f3f8a.gif)

**Comment by VladimirMikulic** [comment]
Awesome! These changes should be pushed in the next release.
