### ISSUE TITLE
File name Error

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/PublicLab.Editor#455]
When uploading the main Image the file name is not changed from "New File Chosen.

![editor8](https://user-images.githubusercontent.com/44112080/78423447-f74c7d80-7683-11ea-8d13-3f31732a72f4.gif)

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @cesswairimu have a look. 
Thanks

**Comment by cesswairimu** [comment]
Tracked on https://github.com/publiclab/PublicLab.Editor/issues/433
