### ISSUE TITLE
Overlapping image and table dialog box

### ISSUE THREAD

**Issue by shreyaa-s** [publiclab/PublicLab.Editor#458]
### Please describe the problem (or idea)
The `add table` menu doesn't close without clicking on the table icon. When image icon or file upload icon is clicked while the table menu is open. They end up overlapping. Maybe a functionality could be added that would close the `add table` menu if the user clicks anywhere other than the table menu itself.
Representation of the same:
![simplescreenrecorder-2020-04-04_13 01 25](https://user-images.githubusercontent.com/55884943/78649046-8226b580-78da-11ea-96d8-c9abb5c773d0.gif)

### Thank you.

**Comment by shreyaa-s** [comment]
@jywarren @emilyashley @cesswairimu please verify the same.

**Comment by NitinBhasneria** [comment]
I think this issue is already described in #407. Please have a look and close this. @shreyaa-s  Thanks

**Comment by govindgoel** [comment]
@shreyaa-s   This issue is already mentioned in the above issue number. Please have a look asap otherwise will be closing this.Thanks

**Comment by shreyaa-s** [comment]
They are similar. I'll be closing this one then. Thanks!
