### ISSUE TITLE
Borders of tables are currently not shown.

### ISSUE THREAD

**Issue by keshav234156** [publiclab/PublicLab.Editor#488]
![Screenshot from 2020-03-07 16-26-09](https://user-images.githubusercontent.com/45951376/81134549-bd1c1780-8f72-11ea-80ae-1a883719f5bb.png)

This should be changed to 

![Screenshot from 2020-03-07 16-24-47](https://user-images.githubusercontent.com/45951376/81134502-978f0e00-8f72-11ea-9f7f-6ecfbdd899eb.png)

**Comment by keshav234156** [comment]
@shreyaa-s Are you currently working on it?

**Comment by shreyaa-sharmaa** [comment]
No, not yet. Are you looking to work on it? If not, I'll be happy to take it.

**Comment by keshav234156** [comment]
@shreyaa-s oK, you can take it.

**Comment by ebarry** [comment]
I'm not sure this is a bug.....it's simply a table that does not have each border drawn. Can anyone explain why they feel this needs to be changed? Thank you!

**Comment by emilyashley** [comment]
Thanks for drawing my attention to this @ebarry  :) 

Curious if anyone has done the discovery and added how tables look and work to the Feature Parity google doc?

**Comment by keshav234156** [comment]
@ebarry Mostly when we draw a table on any editor or elsewhere we usually have for borders around all the four sides of the cell. So it feels like a bug rather than usual behavior.
Thanks!!

**Comment by ebarry** [comment]
Ok, thanks for explaining @keshav234156 . 
I prefer the way tables look on publiclab.org as they currently are, it's a more refined presentation than "every cell is outlined". I think this might be a question we should take out to the community.

**Comment by jywarren** [comment]
Hi, all, the current style is the default for Bootstrap 4, which is covered in our Style Guide: https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab

There are some other variants on the default style including borderless or fully bordered, or zebra-striped, but it seems like folks are OK with the current basic display, so let's close this up! Thanks, all!

https://getbootstrap.com/docs/4.5/content/tables/
