### ISSUE TITLE
Decentering of a centered text

### ISSUE THREAD

**Issue by keshav234156** [publiclab/PublicLab.Editor#489]
If a text has already been centered by a user(and it may happen sometimes by mistake ) then it can’t be uncentered. Also if you want further paragraphs to be uncentered then it’s not possible now.

**Comment by jywarren** [comment]
Just labeling this `bug` -- let's try to do good thorough labeling here! Thank you!

**Comment by shreyaa-s** [comment]
I've made the changes for wysiwyg mode. This is how the center aligning works in markdown.
```js
else if (mode == "markdown") {
      chunks.selection = _module.wysiwyg.parseHTML("<center>"+chunks.selection+"</center>")
    }

    _module.afterParse();
```
Any ideas on how decentering could be implemented in markdown?
Also, how do we need decentering to work in markdown? I think the main purpose of a toolbar in markdown mode is for adding the syntax that the user might not be aware of.  In md the users can easily see and improvise the `->` and `<-` symbols used for centering, then do we need an interface to remove it as well? What do you all think?
cc: @jywarren @keshav234156 @NitinBhasneria @Shulammite-Aso

**Comment by keshav234156** [comment]
I think we should allow de-centering from the toolbar as well as all other modules all allowing it.
we can basically remove ```-> and <-``` from chunks.before and chunks.after
