### ISSUE TITLE
Multiple Add Location Spinners

### ISSUE THREAD

**Issue by shreyaa-s** [publiclab/PublicLab.Editor#493]
![Screenshot_20200506_135924](https://user-images.githubusercontent.com/55884943/81154755-d7b9b500-8fa1-11ea-8fc3-73b2d26756a8.png)

**Comment by NitinBhasneria** [comment]
@shreyaa-s This issue is solved in #436

**Comment by shreyaa-s** [comment]
I'll close this then.
