### ISSUE TITLE
Adding custom inserts

### ISSUE THREAD

**Issue by shreyaa-s** [publiclab/PublicLab.Editor#498]
Adding tools for shortcode syntax.

**Comment by keshav234156** [comment]
similar to #419 . So we can close this

**Comment by shreyaa-s** [comment]
@keshav234156 is #419  only for adding maps or for other features, like buttons, notes, wiki, nodes, activity as well?

**Comment by keshav234156** [comment]
It's a general issue for custom inserts and not specifically for maps

**Comment by shreyaa-s** [comment]
Okay.
