### ISSUE TITLE
refactor and optimize History module

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#50]
figure out where most time is spent

Temporary fix is to limit to 10 past versions, and/or one version per title if more than 1 day old?

**Comment by jywarren** [comment]
Optimization in #61; only most recent 20 shown

**Comment by rexagod** [comment]
@jywarren Hey, can you elaborate on this? What's the problem exactly?

**Comment by jywarren** [comment]
I think it was just a bit messy, to be honest. Perhaps this is no longer a
priority?

**Comment by jywarren** [comment]
I'm going to close because i think the history module is doing OK for now. Thanks!
