### ISSUE TITLE
Adding a linting tool

### ISSUE THREAD

**Issue by keshav234156** [publiclab/PublicLab.Editor#502]
Eslint and Husky: 
Eslint is a tool for identifying and reporting patterns faced in ECMAScript/JavaScript Code,with the goal of making the code more consistent. In order to force the contributor to use Eslint before they commit their code we will use Husky

Eslint and Husky where previously used in Image-Sequencer project. We can think of other alternative tools if it doesn't work here.

**Comment by govindgoel** [comment]
This is great but I think we can also add [Lint-Staged](https://www.npmjs.com/package/lint-staged) as it can check staged files only and later we require to only lint the files that will be committed.

**Comment by jywarren** [comment]
Ooh this is cool. Thanks @govindgoel for the input too!

**Comment by emilyashley** [comment]
I was adding comments on the PR, but wondering if I should post them here instead? 

This is definitely a good part of Step 2 in our Collaboration doc! 

> 2) What would we like as developers to safely change (i.e. conversely what NOT to break!) and develop on the project? (testing, issue templates? CI, github milestones/projects etc) 

🎉🎉🎉

And I'd love to get the whole team's buy in on the tools we use especially if they're saved as part of the project in version control. cc:  @Shulammite-Aso @shreyaa-s @NitinBhasneria
