### ISSUE TITLE
Adding Test suite

### ISSUE THREAD

**Issue by keshav234156** [publiclab/PublicLab.Editor#503]
Integrating the jest-puppeteer for testing and writing tests in a similar way to that implemented in Image-Sequencer. Jest-puppeteer facilitates Keyboard Typing and Mouse simulation so would be best suitable here as well.  
Adding test For Bold Formatting 
Adding test For Italic Formatting

Jest-puppeteer was previously used in the Image-Sequencer project and they work flawlessly. So we can implement it here as well

**Comment by shreyaa-sharmaa** [comment]
Can you give more detail about the test you're talking about? What would the test stimulate?

**Comment by keshav234156** [comment]
the test would simulate various test cases, like for Bold it can simulate that if we press the bold button and text s selected then does it do bolding/un-bolding of text. Similarly, there can be various test-cases

**Comment by shreyaa-sharmaa** [comment]
So we would have two types of test or would we shift the existing tests to jest-puppeteer?

**Comment by shreyaa-sharmaa** [comment]
Hey @keshav234156 are you working on this or can I take this one?

**Comment by keshav234156** [comment]
yes, you can take this
