### ISSUE TITLE
Drag and drop file or image improvement.

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/PublicLab.Editor#504]
1. Presently, when we drag and drop the image in the main image module the editor module will appear grey. This should not happen. The expectation is this: the grey part should only appear when image is dragged to the editor module only.
2. Second, when the file is dragged and uploaded in the editor there is a major lag that can be seen. Also, the image uploaded in editor is difficult to resize.

**Comment by shreyaa-s** [comment]
To enable the option to resize images we have to look for a block-based editor approach. It would give the user a lot of freedom over formatting and layout options, and not just for the images but practically everything that a user adds to the editor.

**Comment by NitinBhasneria** [comment]
fixed in jywarren/woofmark#2
