### ISSUE TITLE
Data Embedding. When copied from other sources to the editor.

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/PublicLab.Editor#505]
When the whole text or para is copied from other sources of an editor it is difficult to be pasted as it is.
This should be improved.
Also, firstly the text will appear as originally but after posting it will be changed in matter of format. This is not a good experience for the user. 
This issue will have changes on plots2 repo too.

**Comment by shreyaa-sharmaa** [comment]
Hey @NitinBhasneria, have you thought about how this could be fixed?

**Comment by NitinBhasneria** [comment]
Not yet @shreyaa-sharmaa

**Comment by NitinBhasneria** [comment]
@jywarren @ebarry Confused on how exactly the copied data should appear? Whether it is to appear in the format it is or with the new format that our PL editor follows.
For example when we copy the table from other editors what is expected then. Whether the borders should appear or not.
