### ISSUE TITLE
Updating to Bootstrap 4

### ISSUE THREAD

**Issue by keshav234156** [publiclab/PublicLab.Editor#508]
PublicLab.Editor uses Bootstrap 3 and PublicLab.org uses Bootstrap 4. There is a considerable amount of difference between the both versions of Bootstrap that lead to inconsistencies. So we should update PublicLab.Editor to version 4

**Comment by shreyaa-sharmaa** [comment]
Hey @keshav234156 , can I take this one?

**Comment by jywarren** [comment]
Agreed, this is a good idea!

🎉

**Comment by sashadev-sky** [comment]
closing because the project is now on Bootstrap 4 so it is stale
