### ISSUE TITLE
User workflow for documenting bugs.

### ISSUE THREAD

**Issue by Shulammite-Aso** [publiclab/PublicLab.Editor#509]
Users who may be non-coders need to be able to report bugs they come across while using the editor.

The general "report a bug" option on the publiclab.org footer is not fully optimized for reporting bugs from the editor, as documenting the editor bugs may require more than text description.
 Including screenshots, GIFs and screen recordings will make understanding and reproducing the bugs a lot easier.

**Comment by Shulammite-Aso** [comment]
So for this, i created a simple UI mockup for requesting documentation from users if they happen to find a bug. A link before the footer like  this or something similar:
![editor-doc](https://user-images.githubusercontent.com/48386390/84004138-a181a380-a95a-11ea-8004-f220b1643f35.png)

then when the user clicks on the link, they're taken to form like this or something similar:
![bug-report](https://user-images.githubusercontent.com/48386390/84004365-f2919780-a95a-11ea-9f58-8d550b7eb7fa.png)

i'm just not very sure about how we're supposed to handle the forms when they're submitted. Maybe the web working group should then be able to see and review the reports when they get submitted and then file an issue with the reports if similar issue is not already filed. 
Or is there a way we can automatically convert the reports to github issues?
Or maybe there's another way to do this? i don't quite know.

**Comment by Shulammite-Aso** [comment]
And maybe this shouldn't be for publiclab/post alone, we could also have it on questions and maybe wikis too.

**Comment by keshav234156** [comment]
Great!! According to me, we should record a GIF that would then automatically be converted to github issue. We should also record the keystroke because with only GIF it sometimes becomes difficult to reproduce the bug.

**Comment by Shulammite-Aso** [comment]
Yeah @keshav234156 I just read a little about keystroke logging. I'm just wondering if the user will need to manually install a keylogger on their device? Or can we on our own setup a keylogger that records every users keyboard activities for when we need it?

**Comment by cesswairimu** [comment]
@Shulammite-Aso it is possible to have a template  like we do on plots2 for bugs https://github.com/publiclab/plots2/issues/new?assignees=&labels=bug&template=--bug-report.md&title= also love the gif idea..maybe we can do a combination of both...this sounds exciting :100:

**Comment by ebarry** [comment]
Very cool UI mockup!

**Comment by Shulammite-Aso** [comment]
Yeahh, @cesswairimu the template will be great. Also one for creating fto issues.

I already made a pull request with these templates here #474 It needs to get merged as soon as possible.

Thanks you!!

**Comment by jywarren** [comment]
Hi all, this is a great start! My thoughts are:

1. perhaps we can achieve this through the existing template system, which inserts markdown formatting into the editor: http://publiclab.org/templates (see how each button opens something like `https://publiclab.org/post?n=15139&title=Your%20issue%20name%20here`) where the title is in text but the preset body content is pointing to another page, in this case, https://publiclab.org/n/15139 ?
2. i love the Gif idea @keshav234156 -- perhaps for now this has to be in the form of a template note, like "add a GIF using this program" or something - building on the resources in our GitHub templates perhaps? Actually we should link to https://github.com/publiclab/plots2/issues/3513 or copy in links to common easy GIF programs. 
3. @cesswairimu and @Shulammite-Aso you're SO RIGHT this is totally a mirror of the GitHub templates and using plots2 templates can make this even more similar -- both would use "default" markdown
4. i do like the idea of posting to GitHub and we do have an IFTTT.com "applet" to repost from http://publiclab.org/issues to GitHub when you click "Ask a question" on that page. You know, here is what they look like: https://github.com/publiclab/plots2/search?q=autoposted&type=Issues (although I think we disconnected this service; we could re-connect it if you like?)
5. shall we in particular have a custom template for issues related to the editor? Is it different enough? 

Thanks, all!

**Comment by jywarren** [comment]
Great work all! Great brainstorming!!!

**Comment by Shulammite-Aso** [comment]
Yes, @jywarren I think if we're using the template method, we will need to to create a different template for editor issues. And maybe link the template to a `report a bug` button from the editor.

I saw there is a "Create a New Template" option here  http://publiclab.org/templates , that is what we should use right?
It takes me to the wiki editor,  so I guess I should create the report template there and hit publish.  I don't actually know what happens after that, does it just make a template and add it to http://publiclab.org/templates or publish a wiki on the publiclab dashboard?? 

Thank you!!!

**Comment by jywarren** [comment]
Yes, so basically you write a wiki page whose content will be used as the template. See how the `n=0000` value in the URL parameters (like `https://publiclab.org/post?n=15139`) points at a wiki page? That wiki page content is what is then used as the template. So once you make a template, just test it out by inserting the wiki page's unique `nid` (you can find this in the page permalink) into the URL where `0000` is shown here:

https://publiclab.org/post?n=0000

**Comment by jywarren** [comment]
Great work! This will be awesome!

**Comment by Shulammite-Aso** [comment]
Thanks @jywarren, this is helpful.

**Comment by Shulammite-Aso** [comment]
> @Shulammite-Aso it is possible to have a template like we do on plots2 for bugs https://github.com/publiclab/plots2/issues/new?assignees=&labels=bug&template=--bug-report.md&title= also love the gif idea..maybe we can do a combination of both ?...this sounds exciting

I think i'm just now understanding what you meant here @cesswairimu, it went over my head a bit earlier. You were suggesting that we use the same bug reporting template we have in plots2 for this editor user bug report?   I had thought you meant having a bug template (via a template chooser, perhaps) for publiclab/PublicLab.Editor/ repo.  

Yes, we are going to be having the same or very similar template, the only difference will be this one won't be on github.

Thank you!!!

**Comment by Shulammite-Aso** [comment]
Have created a template here https://publiclab.org/wiki/editor-bug-report-template and made a PR here https://github.com/publiclab/PublicLab.Editor/pull/530 containing an editor report-a-bug button.

**Comment by ebarry** [comment]
Looks great 🌟! When the template is ready to use, please comment on @emilyashley 's post with the info! https://publiclab.org/questions/emash/06-01-2020/how-do-you-write-and-post-in-the-public-lab-community-asking-for-our-developers
