### ISSUE TITLE
Some styled/custom HTML gets destroyed when converted to Markdown

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#512]
When we create links with button styles, like this:

```html
<a class="btn btn-primary" href="https://publiclab.org">Test button</a>
```

and insert them into the editor in markdown mode, they'll appear as buttons following Bootstrap classes: http://getbootstrap.com/

But if we switch to Rich text mode, that gets converted to:

`[Test button](https://publiclab.org)`

And the styles are lost. Perhaps we should try to detect if classes exist and not disturb them? This might require a change to the upstream `woofmark` editor module. What do you think?

**Comment by Shulammite-Aso** [comment]
figured out this is from not specifying "class" as an allowed attribute for links here: https://github.com/publiclab/PublicLab.Editor/blob/588305495e99d2681b691f76fb3d6feacd477915/src/adapters/PublicLab.Woofmark.js#L218

will make a PR.
