### ISSUE TITLE
inconsistency with history icon.

### ISSUE THREAD

**Issue by Shulammite-Aso** [publiclab/PublicLab.Editor#527]
### Please describe the problem (or idea)

I think we need to choose which icon to stick with and make the needed adjustment. 

![Screenshot from 2020-06-08 19-43-50](https://user-images.githubusercontent.com/48386390/84076151-cb6fb000-a9c4-11ea-9c88-9e9bb44be82e.png)

Then this can also be made a `first-time-only` issue, once we know which to go with.

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ebarry** [comment]
Good catch! We can either 
- [ ] use https://fontawesome.com/v4.7.0/icon/clock-o everywhere, and remove the '...' entirely
- [ ] change the lower left hand menu icon to '...'

I have a slight preference for changing the menu's own label to '...' because i do not find it intuitive to click a clock to find previous saved versions. I would recognize a '...' or three horizontal bar "hamburger" icon to indicate that stuff is stored in there. Thoughts?

**Comment by Shulammite-Aso** [comment]
I think what was missing from the previous `...` was a tooltip. If we add add tooltip to it, `...` will be okay, in my view.

**Comment by ebarry** [comment]
hmm, would the tooltip contain the clock icon? I do not see how a tooltip would solve this problem, but perhaps i am just not understanding.

**Comment by Shulammite-Aso** [comment]
Oh, actually meant that returning the history icon to what it was before which is this `...` (as against the clock icon) should work, if we make a tooltip for it.

**Comment by ebarry** [comment]
ah, i understand! that sounds great, thanks for explaining to me 🤝

**Comment by shreyaa-sharmaa** [comment]
Good catch @Shulammite-Aso !

**Comment by jywarren** [comment]
Hi all! We actually recently changed to the clock icon with input from @publiclab-mimi -- so, I think the best course may be to change the `...` to a clock icon, to go with this more recent requested icon style! Thank you all!

One way to look for this kind of thing if you don't happen to know which to go with is to look at the "blame" view in GitHub to see what change was more recent. Blame is a terribly inaccurate name! But it's a useful feature :-)

Thanks!

**Comment by jywarren** [comment]
And great catch, @Shulammite-Aso !

**Comment by ebarry** [comment]
great! let's go with the clock!

**Comment by Shulammite-Aso** [comment]
Oh, okay!  will open a first time only issue with this then.

**Comment by shreyaa-sharmaa** [comment]
Closing this with #576
