### ISSUE TITLE
Move all PRs to `main` branch instead of `master`

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#535]
Hi, all! We've been in the midst of a years-long series of migrations from using a branch called `master` as default to `main`, and although we've succeeded for many of our repositories (https://github.com/publiclab/mapknitter/, https://github.com/publiclab/spectral-workbench/, for example), we haven't done this repo yet. This is important because of the racist connotations of the term `master` especially in the US. 

One complicating issue that's slowed us in the past is that it requires re-assigning all PRs to the new default branch. But there is now (recently) a feature for this in GitHub:

![image](https://user-images.githubusercontent.com/24359/84805632-8eae4500-afd2-11ea-987e-4d1e8af35a33.png)

Let's start this process -- I've just reassigned the default to `main` and we should be able to re-assign all PRs accordingly. Thanks, all!

**Comment by jywarren** [comment]
Just did this for https://github.com/publiclab/PublicLab.Editor/pull/534 - thanks!!! cc @NitinBhasneria

**Comment by jywarren** [comment]
and in #533 - great!

**Comment by jywarren** [comment]
I believe we're done here! Thanks, all!

**Comment by morrme** [comment]
thank *you*.
