### ISSUE TITLE
Document/refine autocompletion code

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#55]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

GCI students are requested to go through the conversation and understand it before jumping to the implementation. The conversation will help them to debug it.

maybe break out into independent submodule?

**Comment by jywarren** [comment]
This is done -- you can turn it on and off in these lines:

https://github.com/publiclab/PublicLab.Editor/blob/e997bc0586c2e26ef76d85269228235d038d0586/examples/autocomplete.html#L233-L235

I'm going to change this to a documentation issue:

After @rexagod completed https://github.com/publiclab/PublicLab.Editor/pull/239, I wanted to enable this in `plots2`, so I think i need to turn off the disable settings here:

https://github.com/publiclab/plots2/blob/fe50428f4c56f12fcea92ae76343346d0421da70/app/views/editor/rich.html.erb#L326-L327

I'll try this out, but let's think about expanding the docs with a short section demonstrating this!

**Comment by jywarren** [comment]
Do we need to comment these out? 

https://github.com/publiclab/PublicLab.Editor/blob/e997bc0586c2e26ef76d85269228235d038d0586/examples/autocomplete.html#L233-L235

**Comment by jywarren** [comment]
Perhaps we should also look to integrate this more tightly into the codebase -- say, if a function is provided for `tagsAutocomplete` or `authorsAutocomplete`, we could automate this integration code:

https://github.com/publiclab/PublicLab.Editor/commit/79f331f2e3b99e5f8baa0fbd25a60036962b6e8c#diff-3f8a176e88c67f375d6f19116e6addedR1

Alternatively, we could allow people to pass in an object to set up multiple types, as in:

```js
richTextModule: {
  autocomplete: {
    '@': {

  callbacks: {
    formatter: function(value, obj) {
      // interfacing formatting code
      return value;
    },
    remoteUrl: function(query, callback) {
      $.getJSON(
        "https://publiclab.org/api/srch/tags?query=" + query,
        {},
        function(data) {
          if (data.hasOwnProperty("items") && data.items.length > 0) {
            callback(
              data.items.map(function(i) {
                return i.doc_url;
              })
            );
          }
        }
      );
    }
    }
  }
}
```

What do you think, @rexagod ?

**Comment by jywarren** [comment]
Docs are merged, and look great!

@rexagod i know you're interested on taking the integration one step further, but you're doing a lot already! Don't overdo it! 😄 Perhaps @vladdypwnz is interested in helping out here?

**Comment by jywarren** [comment]
https://github.com/publiclab/PublicLab.Editor#atwhojs-data-module

**Comment by jywarren** [comment]
This looks great, I think we need to change it so it allows linking to a tag using `#abcde` with letters, and to any node in format `/n/12345` from any entry of `#12345` using numbers!

We'd love help with this as a follow-up, and THEN we can begin integrating this into https://github.com/publiclab/plots2/ !

**Comment by CodeSarthak** [comment]
I'm sorry but can someone briefly explain to me what is happening and what is our objective here now?

Thank you for the help.

**Comment by jywarren** [comment]
Thanks! I think the next step here is to get it to recognize if the characters following the `#` are purely integers, and if so, have it link to a URL in the format `/n/______` - like it works on GitHub! 

but if there are any letters in it, then it gets treated like a hashtag on Twitter, and we link to `/tag/______` instead. 

These two URL formats are for page permalinks (https://publiclab.org/n/21410) and tag list pages (https://publiclab.org/tag/water-quality), respectively. 

The overall system is explained here! https://github.com/publiclab/PublicLab.Editor/#atwhojs-data-module 

I think the changes to the hashtag pattern need to be made here to switch between the two types: 

https://github.com/publiclab/PublicLab.Editor/blob/7b8a5f82149b88a52ee60ae516212917d23df723/examples/data/atwho.PLE.js#L34-L46

Then, we can do a follow-up issue to integrate this functionality into `plots2` https://github.com/publiclab/plots2/

**Comment by VladimirMikulic** [comment]
@jywarren I already have a possible implementation of this, but how should I test it?
PublicLab doesn't have posts with tags like #10980, #105957...

**Comment by VladimirMikulic** [comment]
@jywarren I think that your API is not working correctly.

![Screenshot_20191215_173037](https://user-images.githubusercontent.com/35997844/70865727-fec70a00-1f60-11ea-977d-589309cc7d39.png)
![Screenshot_20191215_173123](https://user-images.githubusercontent.com/35997844/70865729-02f32780-1f61-11ea-8842-a84f1fd70f18.png)

As you can see note does exist, but API is unable to find it.

**Comment by jywarren** [comment]
Ah, ok! So, for some autocompletions, we do need to show matching tags, for
example if you start typing #ball, we should see "suggestions" for #ball,
#balloon, #ballerina. But for numerical ones, in GitHub, we actually see
titles; in the plots2 API I am not sure that our Api actually allows
searching by node ID, which is why you aren't getting any results for the
numerical version here.

Why don't we split out to 2 behaviors as you begin to type; if it includes
non-numeric characters, we do a search using the tag endpoint here, which
is nice and fast and optimized:

https://github.com/publiclab/plots2/blob/731b1c6910bf8b44445fbee2a8724270eeca0a4e/app/assets/javascripts/restful_typeahead.js#L23

If it includes ONLY an integer, like #12345, we don't display
autocompletion results. Can we do that and skip the API call for that one?
Only show autocompletion if we are NOT an integer?

Thank you!

**Comment by VladimirMikulic** [comment]
@jywarren thank you for shining a light on this. You should expect a PR soon :)

**Comment by jywarren** [comment]
Thank YOU!

:-)
