### ISSUE TITLE
When dragging and dropping, image URL prompt flashes then disappears quickly

### ISSUE THREAD

**Issue by ebarry** [publiclab/PublicLab.Editor#56]
I'm using the publiclab.org/editor and it's very nice. 

When i drag and drop images, the image URL prompt displays for a short time, i think while the image is uploading -- it seems to request information like adding a link URL but the issue i am reporting is that this prompt disappears before i can actually read it or type into it. I had to be fast even to capture this screenshot of it!

![screen shot 2016-10-26 at 10 11 42 am](https://cloud.githubusercontent.com/assets/161439/19729469/17782b20-9b65-11e6-9596-92b090ea33ca.png)

Actually, if i had wanted to add a link to the image, and i had missed my chance during this flash, i am not sure how to get this popup back.

**Comment by jywarren** [comment]
Can you break this into separate issues please? Thanks!

**Comment by jywarren** [comment]
This dialog is not for adding links to images -- it's just for inserting new images; the URL requested would be the URL of an image to display. I believe you can select an image and click the link button, or control-K? If so, can you close this issue?
