### ISSUE TITLE
Moving images throws an error alert but nothing is actually broken

### ISSUE THREAD

**Issue by ebarry** [publiclab/PublicLab.Editor#58]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

When i try to move an image that has already been uploaded/embedded, it gives this error although there's nothing really wrong with the image: 

![screen shot 2016-10-26 at 10 12 04 am](https://cloud.githubusercontent.com/assets/161439/19729551/5840066e-9b65-11e6-910b-eda26dcd54de.png)

**Comment by jywarren** [comment]
Hi Liz, how do you move the image? Cut and paste?

**Comment by jywarren** [comment]
Hi @ebarry, can you elaborate on this please? Thanks!

**Comment by rexagod** [comment]
@ebarry Can you reproduce this in a gif for us, or just state the steps that led you to encounter this error? Thanks!

**Comment by SidharthBansal** [comment]
PUBLISHED to GCI dashboard

**Comment by tsparksh** [comment]
How can I reproduce this issue? Everythig seems ok for me
![images](https://user-images.githubusercontent.com/17945250/70589852-7284b200-1c03-11ea-8716-5e769f6fab36.gif)

**Comment by jywarren** [comment]
Maybe @ebarry can specify better but I wonder if she means moving an image
from one position in the text area to another? Can you try entering some
paragraphs of text and trying to move the image either by dragging it or by
copy-pasting? @ebarry how exactly did you move the image? Thanks all!

**Comment by VladimirMikulic** [comment]
@jywarren I am able to reproduce the issue. Upload the image and then try to move it, you'll get an error modal. Unfortunately, this is not fixable from our side.
The best thing that we can do is to prevent moving images once they are uploaded.

What do you think? Should I implement it?
Thanks.

**Comment by tsparksh** [comment]
> @jywarren I am able to reproduce the issue. Upload the image and then try to move it, you'll get an error modal. Unfortunately, this is not fixable from our side.
> The best thing that we can do is to prevent moving images once they are uploaded.
> 
> What do you think? Should I implement it?
> Thanks.

May be we can disable events for dragover hover box while moving images and reenable them onmouseup?

**Comment by VladimirMikulic** [comment]
@tsparksh handling events is not a problem. Let's just wait for @jywarren's opinion on this matter.

**Comment by jywarren** [comment]
@VladimirMikulic when you moved the image did you drag it from one area to another? Copy paste it? 

If dragging, maybe @tsparksh's idea could work. Is the failure mode that it tries to re-upload when you end your drag?

**Comment by VladimirMikulic** [comment]
@jywarren you've misunderstood me. When I said 'handling events is not a problem', what I meant about it was that it's easy. I wasn't against @tsparksh's idea, I mean that's the only way we can solve it.

[Demo](https://streamable.com/1domu) on how the issue occurs.

**Comment by jywarren** [comment]
sounds great! Just wanted a little more clarification. Awesome work, all!
