### ISSUE TITLE
More compact design for main image module

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#592]
Hi all, I wanted to request a more compact design for this section, especially on narrower screens. See how the buttons could be side by side and a bit smaller?

![image](https://user-images.githubusercontent.com/24359/90045527-29f32c00-dc9d-11ea-971b-9b6373efcd18.png)

The older design had fewer buttons but it was more compact, and I think we could get closer to that amount of space:

![image](https://user-images.githubusercontent.com/24359/90045616-4d1ddb80-dc9d-11ea-80f1-141bbe2b2f07.png)

Who would like to try to take this up? I think it's primarily CSS. Thanks all! cc @publiclab/editor @sagarpreet-chadha

**Comment by shreyaa-sharmaa** [comment]
Can I take it up @jywarren ?
