### ISSUE TITLE
Main image upload module working? 

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#593]
Did anything change about how main images are uploaded? I am seeing an error on https://stable.publiclab.org/post when selecting an image:

But not when uploading an image to a comment box, so I think it may be the JS => Ruby connection in the editor that's changed. 

https://stable.publiclab.org/notes/anngneal/12-08-2017/7-ways-to-measure-monitor-and-evaluate-water-quality

The upload itself seems OK, and I see a progress bar, and I see that the image URL, although it's a seemingly correct URL, returns an error. 

For example, i uploaded an image: 

![light:dark detector](https://user-images.githubusercontent.com/24359/90046190-1f856200-dc9e-11ea-8ce3-72c30b23ba3f.png)

But this URL which was returned, doesn't exist: https://stable.publiclab.org/system/images/photos/000/040/099/original/light_dark_detector.png

I think the best way to debug this may be to inspect the XHR request that sends the image up in the live site, https://publiclab.org/post, and compare it carefully to what https://stable.publiclab.org sends. 

We can also inspect any changes to https://github.com/publiclab/PublicLab.Editor/blame/main/src/modules/PublicLab.MainImageModule.js to see if there is any reason it might have changed what's sent. Although we can certainly confirm that the server is receiving the file, as we see it has the filename when it responds with the broken URL. 

Can I get a volunteer for this? I think it's a pretty critical one, so I want to prioritize it! cc @publiclab/editor @sagarpreet-chadha 

It may also be worthwhile testing this out in GitPod: https://gitpod.io/#https://github.com/publiclab/plots2/

**Comment by jywarren** [comment]
OK! I believe this may be an issue with Stable server -- it's working fine in GitPod!!!

![image](https://user-images.githubusercontent.com/24359/90048496-9a9c4780-dca1-11ea-8d40-a1a1907b7c8b.png)

OK, but let's be VERY careful when publishing. @icarito can you confirm any possible issues with image upload on stable? Note comment image upload is indeed working. Maybe we can pull errors from stable to see what happened? 

Reproducible at https://stable.publiclab.org/post on main image upload.

**Comment by icarito** [comment]
Thanks for the details. The logs are accessible at:
https://jenkins.laboratoriopublico.org/job/Plots-Stable/ws/log/production.log/*view*/

I'll try to reproduce and see what happens.
--
Sebastian Silva

**Comment by ebarry** [comment]
How's this one going, everyone?

**Comment by RaviAnand111** [comment]
hey @jywarren @TildaDares , did this issue got solved or not?,

**Comment by TildaDares** [comment]
Hi @RaviAnand111, I think the main image upload is working on publiclab.org but you can test it yourself just to be sure.

**Comment by RaviAnand111** [comment]
Sorry for asking dumb questions, 
but should I check on my local publiclab.Editor app or on publiclab.org website itself ?

**Comment by TildaDares** [comment]
@RaviAnand111 There are no dumb questions. Check on publiclab.org

**Comment by RaviAnand111** [comment]
hey @TildaDares on publiclab.org, I cannot find rich text editor or anything around that, how can I try uploading image ?

**Comment by TildaDares** [comment]
@RaviAnand111 Visit https://publiclab.org/post

**Comment by RaviAnand111** [comment]
I can't login 

![image](https://user-images.githubusercontent.com/59113935/148361034-228e7363-41e7-4f5f-8a85-22df97623dc3.png)


user password is giving this error

**Comment by RaviAnand111** [comment]
with admin password I am on main page again, 

![image](https://user-images.githubusercontent.com/59113935/148361243-11b10a2c-3ac7-4f48-8e2a-f8435d241629.png)

**Comment by TildaDares** [comment]
@RaviAnand111 Did you signup with a Google account?

**Comment by RaviAnand111** [comment]
No I didn't, I will do that now.
and update you.

**Comment by RaviAnand111** [comment]
Hey, @TildaDares thanks for helping with the process, 
I tried to upload image and it is working fine.

![image](https://user-images.githubusercontent.com/59113935/148362575-426e0379-04fb-456f-b178-a3656c3baf0b.png)

ThankYou

**Comment by TildaDares** [comment]
I think this issue can be closed now.

**Comment by RaviAnand111** [comment]
ok, ThankYou

**Comment by RaviAnand111** [comment]
Hey @TildaDares I wanted to ask a doubt, the local publiclab editor I have is different from the publiclab.org/post website why is that ?

**Comment by TildaDares** [comment]
@RaviAnand111 That's because the editor page for `publiclab.org` has its own design that is slightly different from the one in this repo. You can take a look at the different HTML files for `publiclab.org` and `publicLab Editor`

https://github.com/publiclab/PublicLab.Editor/blob/main/examples/index.html
https://github.com/publiclab/plots2/blob/main/app/views/editor/rich.html.erb
