### ISSUE TITLE
Uploaded main images are displayed oddly

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#596]
On plots2, (https://github.com/publiclab/plots2/pull/8297 in gitpod), I uploaded a main image but it displayed a bit weird. I'm wondering what the best way to organize the buttons and image is after upload? 

![Screen Shot 2020-08-14 at 5 58 45 PM](https://user-images.githubusercontent.com/24359/90295782-d6790d80-de57-11ea-9dd0-ab813fa7ccc4.png)

Love to hear your thoughts!

**Comment by shreyaa-sharmaa** [comment]
I tested it out in gitpod too and the main image box looked fine before uploading the image but changed after uploading the image 
![imgtrue](https://user-images.githubusercontent.com/66686803/90298317-7b730500-deaf-11ea-905d-f829b0af9409.png)
![img](https://user-images.githubusercontent.com/66686803/90298318-7d3cc880-deaf-11ea-8a48-8c13a3f8df97.png)

**Comment by sagarpreet-chadha** [comment]
@publiclab/editor team, would anyone want to take a look at this, seems like a `CSS` fix that we need to do. Thanks in advance 🎉 💯

**Comment by daemon1024** [comment]
Is this issue open to work on? 

I was trying to recreate the issue but when I tested it out on gitpod but it seemed to get stuck at 100% progress bar.

![image](https://user-images.githubusercontent.com/47106543/92333219-977a5880-f0a1-11ea-884b-b0fe538ea0ab.png)

**Comment by sagarpreet-chadha** [comment]
You can try reproducing this on `publiclab.org` then, if this issue still persists then you can take forward and solve it 😄 . Thanks 💯

**Comment by daemon1024** [comment]
@sagarpreet-chadha I can reproduce it on publiclab.org.I thing i have the solution to it but I am unable to figure out how do I test it out after fixing it due to the problem I mentioned in the previous comment?

**Comment by sagarpreet-chadha** [comment]
Did you try running this project locally?

**Comment by daemon1024** [comment]
@sagarpreet-chadha i just found how to test image-upload ( https://github.com/publiclab/PublicLab.Editor#creating-a-mock-server ), I am trying this now

**Comment by daemon1024** [comment]
@sagarpreet-chadha it works :) can you review the PR?

**Comment by jywarren** [comment]
Thank you so much for your help on this!!! 🎉 🎉 🎉
