### ISSUE TITLE
Preview for small leads images is tiled

### ISSUE THREAD

**Issue by ebarry** [publiclab/PublicLab.Editor#60]
I uploaded this small image to the main image box on the Editor: 

![screen shot 2016-10-26 at 2 45 15 pm](https://cloud.githubusercontent.com/assets/161439/19739983/f277efc4-9b8a-11e6-9d38-97d75c84fa7c.png)

and the preview showed this: 

![screen shot 2016-10-26 at 2 45 33 pm](https://cloud.githubusercontent.com/assets/161439/19739991/f9c04ef2-9b8a-11e6-9047-8bdff2c1f99c.png)

But this is not a real problem because once published, the lead image was not actually tiled.

**Comment by jywarren** [comment]
Fixed in #63, thanks!
