### ISSUE TITLE
Toggling between Rich and Markdown loses extra carriage returns in numbered lists

### ISSUE THREAD

**Issue by ebarry** [publiclab/PublicLab.Editor#62]
When returning to rich mode from a brief dive into markdown mode, the carriage returns (which i placed after each numbered item to add white space between the bottom of the screenshot from the top of the next instruction) were lost. Not a big deal here, easy to work around this, but reporting it because it was unexpected behavior

**Comment by jywarren** [comment]
Did it return to being a continuous ordered list? Could be a related issue
to the other ordered list one.

**Comment by jywarren** [comment]
I believe this is because in Markdown, carriage returns are not allowed between list items; this makes them into separate lists. This is the same as what's happening in #59, so merging.
