### ISSUE TITLE
Misaligned placeholder text in https://publiclab.org/post

### ISSUE THREAD

**Issue by daemon1024** [publiclab/PublicLab.Editor#623]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

![image](https://user-images.githubusercontent.com/47106543/94483524-9c41b080-01f8-11eb-90a4-922105dc4510.png)

> What did you expect to see that you didn't?

the placeholder text should be insides the box

### Please show us where to look

https://publiclab.org/post

### What's your PublicLab.org username?
barun1024
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome , Firefox , Windows , NixOS 
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by daemon1024** [comment]
This can be reproduced if https://github.com/publiclab/PublicLab.Editor/blob/e7671c078d26747388cabb194873333ab252e260/examples/index.html#L271
placeholder attribute is added to the above tag in example/index.html

**Comment by dharmelolar** [comment]
Hello @daemon1024 can i work on this fix? I just checked now and the issue has not been solved
![Screenshot (3)_LI](https://user-images.githubusercontent.com/53821931/95980594-4898af00-0e15-11eb-9de1-06fb5ce51416.jpg)

**Comment by daemon1024** [comment]
@dharmelolar Sure.

cc @publiclab/editor

**Comment by dharmelolar** [comment]
Hello @daemon1024 after fixing the bug in this issue, I realized there'still something that needs to be done, even after fixing the bug, this text still shows in the textarea.
![Screenshot (5)](https://user-images.githubusercontent.com/53821931/96235691-fe3d3c80-0f92-11eb-8dc5-928ba851196f.png)

**Comment by dharmelolar** [comment]
But after deleting this text in my editor, the code work perfectly.
![Screenshot (6)](https://user-images.githubusercontent.com/53821931/96236091-7e63a200-0f93-11eb-859e-e0a6abe602d8.png)
![Screenshot (4)](https://user-images.githubusercontent.com/53821931/96236126-8a4f6400-0f93-11eb-90eb-e40393c2e55b.png)

**Comment by dharmelolar** [comment]
Please kindly advice

**Comment by Sagarpreet** [comment]
Hey @dharmelolar , thanks for investigating but this is solved in https://github.com/publiclab/PublicLab.Editor/pull/635
You can try the gitpod link in that PR to verify this: https://a15099a1-0d3a-4e36-bd91-aa4ce8a78b5c.ws-us02.gitpod.io/#/workspace/PublicLab.Editor
Thanks for the help 😄 Looking forward to have you contribute in any other issue 🎉

**Comment by ebarry** [comment]
Thank you both!
