### ISSUE TITLE
Weekly Community Check-In # 78- Create ftos for Outreachy aspirants

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/PublicLab.Editor#634]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Create ftos for Outreachy aspirants

We are out of available first-timer-only(fto) issues and we are having more applicants coming in. This week please take a moment to create some ftos so that we can make sure they get the help they need to get started.You could also convert issues with `fto-candidate` `good-first-issue` labels to a fto or break up an existing issue to multiple ftos. This can be done across all our active projects. You could add an `outreachy` label to reserve it for the Outreachy aspirants. Once done, kindly mention the issue on the [Outreachy welcome issue](https://github.com/publiclab/plots2/issues/8448) so that folks waiting for ftos could be notified. Thanks everyone in advance :100: 

### Thank you note to focus issues contributors
Many many thanks to everyone who created ftos, helped with reviews, issue clarifications and support to help the new conttributors get started :heart: in the past two weeks.  :1st_place_medal: :1st_place_medal: @jywarren , @renugasaraswathy,  @RuthNjeri  @avats-dev @Tlazypanda, @ebarry  @sagarpreet-chadha  :1st_place_medal: :1st_place_medal:  and anyone else I may have missed :1st_place_medal: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart: 
Have a great week all :balloon:

**Comment by RuthNjeri** [comment]
Hi @cesswairimu thank you so much for being responsive to our many many queries. A big thank you as well to @jywarren who has also answered so many questions as well. 

I have really enjoyed creating my first PR for the Outreachy application and I am hoping in the next few weeks to touch on a couple of frontend tasks and bugs as well and begin writing my proposal in the coming week.

I would love to open the next check-in.

**Comment by jywarren** [comment]
Yes! Whoa, it's been a lot of activity in the past few days! And I do see folks creating their own `first-timers-only` issues to welcome other newcomers -- that's so special and we are really impressed and appreciative of everyone who's reached out to help in this way. Great work, everyone!

**Comment by cesswairimu** [comment]
@RuthNjeri feel free to open the check-in anytime today. You can find the template at  https://github.com/publiclab/plots2/issues/new/choose `Weekly Check-in` . Feel free to ping me if you need any help. Thanks

**Comment by RuthNjeri** [comment]
@cesswairimu I am thinking of mentioning "Outreachy Proposal" as this week's focus, is that a valid one?

**Comment by RuthNjeri** [comment]
Also, should I post the weekly check-in in the Plots2 repo or in this one(PublicLab.Editor)?

**Comment by cesswairimu** [comment]
Hey @RuthNjeri , yeah its a good one. You can open on either of the repos

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8619. Thanks all
