### ISSUE TITLE
github.io link on github page 404s

### ISSUE THREAD

**Issue by fwolfst** [publiclab/PublicLab.Editor#643]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The link on the github page ("About" section) to https://publiclab.github.io/PublicLab.Editor/examples/ gives a 404 .

> What did you expect to see that you didn't?

I wanted to see the example :)

**Comment by jywarren** [comment]
Great catch, and apologies! I think i fixed it by removing `grunt` from the gh-pages branch and rebuilding it: https://github.com/publiclab/PublicLab.Editor/commit/9e4c47784e24dc92bf57fa22f2dfc8bf4640ce7c
