### ISSUE TITLE
Travis taking forever to finish..move to git-actions? 

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/PublicLab.Editor#676]
We moved plots2 to git-actions and the CI is now running seamless...we could attempt to do the same here...
 plots2 PR: https://github.com/publiclab/plots2/pull/8795/

**Comment by jywarren** [comment]
Yes! We def should. I just finished doing it for image-sequencer so here's a possible helpful reference: https://github.com/publiclab/image-sequencer/pull/1783
