### ISSUE TITLE
Entering a link scrolls the page to the start of the textarea

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#69]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Not sure if this is a Woofmark behavior or what? https://github.com/bevacqua/woofmark

but it could be tested in that editor to see; it may be due to a `#` link of some kind being triggered on pressing enter after inputting the URL in the popup form.

**Comment by SidharthBansal** [comment]
PUBLISHED ON GCI DASHBOARD

**Comment by fluctix** [comment]
I am not able to reproduce this error in production.

**Comment by VladimirMikulic** [comment]
@jywarren I can confirm that this is a woofmark default behaviour.
I filed them an [issue](https://github.com/bevacqua/woofmark/issues/71).

**Comment by VladimirMikulic** [comment]
@jywarren Woofmark default behaviour didn't stop me from fixing it :)
