### ISSUE TITLE
* does not work for bullet points in the markdown editor

### ISSUE THREAD

**Issue by Manasa2850** [publiclab/PublicLab.Editor#714]
### Please describe the problem (or idea)
`*` is normally used to denote bullet points in markdown editors. However, in the PL editor using * is shown as * and not as a bullet point.

### Please show us where to look

In the legacy editor https://publiclab.org/post?&legacy=true
In the rich editor https://publiclab.org/post?

**Comment by RaviAnand111** [comment]
hey @Manasa2850 `-` is used for bullet points in PublicLab Editor

**Comment by RaviAnand111** [comment]
hey @TildaDares @jywarren , should this issue be closed or is there anything else to do here ?

**Comment by TildaDares** [comment]
Hi @RaviAnand111, bullet points could either be * or -

Also, I tried using * for a bullet point and it worked. Can you try it on your end just to confirm?

**Comment by RaviAnand111** [comment]
yepp, It is working, so `*` and `-` both can be used for bullet points.

![image](https://user-images.githubusercontent.com/59113935/148356164-8e606965-ad9d-43a5-84e7-1b53f957984c.png)

**Comment by TildaDares** [comment]
I think we can close this now

**Comment by RaviAnand111** [comment]
ok, ThankYou
