### ISSUE TITLE
Set RichText as the default formatting mode in the editor on /post

### ISSUE THREAD

**Issue by imajit** [publiclab/PublicLab.Editor#736]
The default writing mode is set to markdown in the editor. We need to change it to "AaRich" 
![Screenshot from 2021-08-10 03-15-09](https://user-images.githubusercontent.com/38528640/128778614-a4320bf8-e301-41c1-a585-8d4e0f761aba.png)

**Comment by tcvan0707** [comment]
Do you have any suggestions of how to fix this?

**Comment by jywarren** [comment]
I just tried in a new account on publiclab.org, and it defaulted to rich text mode! I think we're OK here! Thank you!
