### ISSUE TITLE
Move all old Jasmine tests to Jest?

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#743]
As we're seeing two different tough Jasmine test failures in https://github.com/publiclab/PublicLab.Editor/issues/741 and https://github.com/publiclab/PublicLab.Editor/issues/721, I propose we move all our Jasmine tests into Jest (our newer test suite) to bypass this issue. 

Most of our tests are quite simple, and will just need some reworking of syntax. Let's discuss and collect resources here.

old Jasmine tests: https://github.com/publiclab/PublicLab.Editor/blob/main/spec/javascripts/

Jest tests: https://github.com/publiclab/PublicLab.Editor/blob/main/test/ui-testing/

Example Jasmine test:

https://github.com/publiclab/PublicLab.Editor/blob/d01e8fbd841e015f9928716cd51b7f22bbeed42e/spec/javascripts/editor_spec.js#L21-L35

Example Jest test:

https://github.com/publiclab/PublicLab.Editor/blob/d01e8fbd841e015f9928716cd51b7f22bbeed42e/test/ui-testing/bold.test.js#L9-L25

Jest documentation: https://jestjs.io/docs/getting-started

**Comment by jywarren** [comment]
So let's start with a simple one. The button tests here:

https://github.com/publiclab/PublicLab.Editor/blob/main/spec/javascripts/button_spec.js

can be moved into its own file; ok, i did this in #744.

The Jest syntax is almost identical in this case. I think we could add this to generate a first-timers-only issue:

```js
  test('publish button gets enabled', () => {
    // Check initially that Publish button is disabled.
    expect($('.ple-publish').prop('disabled')).toBe(true);
    // Add title.
    $('.ple-module-title input').val('A title');
    $('.ple-module-title input').keydown();
    // Check final state of Publish button.
    expect($('.ple-publish').prop('disabled')).toBe(false);
  }, timeout);
```

For other Jasmine files, we can also create corresponding Jest files with similar names - let's use the `camelCase.test.js` format. They'd each get something like this when empty, as a first step:

```js
const timeout = process.env.SLOWMO ? 60000 : 10000;
const fs = require('fs');
beforeAll(async () => {
  path = fs.realpathSync('file://../examples/index.html');
  await page.goto('file://' + path, {waitUntil: 'domcontentloaded'});
});

describe('Publish button', () => {
  // tests go here:

});
```

**Comment by jywarren** [comment]
https://github.com/publiclab/PublicLab.Editor/pull/744 merged! Remember that we dont have to pass the "base tests" which are Jasmine, as those are the stuck ones. We just have to get the newer "ui tests" to pass.

**Comment by TildaDares** [comment]
@jywarren I created an FTO in #746 for the history test. What do you think?

**Comment by jywarren** [comment]
OK, so the tests have to be written in a bit of a weird syntax so this isn't going to be quite as easy:

``js
    const text = await page.evaluate(() => document.body.textContent);
    expect(await page.evaluate('document.querySelector(".ple-publish").getAttribute("disabled")')).toBe(true);
```

**Comment by NARUDESIGNS** [comment]
@jywarren @TildaDares I think I should be able to move some of the tests. I see that `button_spec.js` has been set as FTO so can I start with `history_spec.js` ?
or maybe I should have them listed in my planning issue for the Outreachy internship either way I'm ready to get started!

**Comment by jywarren** [comment]
Hi @NARUDESIGNS thanks for getting in here and sorry for the slow reply. I thought it would be a pretty straightforward thing but as I learned in this PR it seems that the syntax for making direct JS calls into the browser environment is a bit more complex in Jest+Puppeteer, unfortunately: https://github.com/publiclab/PublicLab.Editor/pull/749/

Take a look but once we figure out how they're supposed to be made, converting them all will be pretty easy - even good as FTOs for newcomers! But unfortunately when we tried this the first time we learned that we don't really yet understand how to properly convert them. 

I hope we can figure out how to either choose the correct way of doing jQuery selectors in the browser env, OR wrap them in something that gets us into the browser context, OR prefix them with something that makes it work. But I'm worried that the syntax will be long and not very easy to read... Let's work this problem as I think it will unlock the whole testing project for us!

**Comment by jywarren** [comment]
I think we just need to try a bunch of variations until we can see that the test runs correctly and tests the things we're trying to monitor. I think it's best to try getting them running in the commandline rather than continuing to push up new commits to wait for GitHub Actions to run them - that'll make it faster to try lots of different options.

**Comment by NARUDESIGNS** [comment]
> #744 merged! Remember that we dont have to pass the "base tests" which are Jasmine, as those are the stuck ones. We just have to get the newer "ui tests" to pass.

Let me be sure we are on the same page. This only includes the initial template for the file (which all jest files should have, just like you mentioned) but not the actual test cases from the corresponding Jasmine file right?

**Comment by jywarren** [comment]
Yes, well at this point i'm trying to get /any/ jQuery or equivalent selector/assertions to run or pass or even fail!

**Comment by NARUDESIGNS** [comment]
@jywarren I tried adding 
```
const { JSDOM } = require("jsdom");
const myJSDom = new JSDOM ();
const $ = require('jquery')(myJSDom.window);
```
at the top of the test file, which I learnt about from - [this conversation](https://stackoverflow.com/questions/21358015/error-jquery-requires-a-window-with-a-document#:~:text=const%20%7B%20jsdom%20%7D%20%3D%20require(%22jsdom%22)%3B%20const%20myjsdom%20%3D%20new%20jsdom%20(html)%3B%20const%20%24%20%3D%20require('jquery')(myjsdom.window)%3B)
and it stopped complaining about the "$" symbol but the test now fails. Have a look at this screenshot

![Screenshot 2021-12-08 at 08 58 32](https://user-images.githubusercontent.com/49737323/145170740-6234a00d-2138-4d3b-b28a-702ff9a9c940.png)

**Comment by RaviAnand111** [comment]
Hey @NARUDESIGNS @jywarren @TildaDares , can I help you guys too, I do not know much about testing but I know javascript and I am willing to learn, contribute and help, is there something I can do ?
Thanks

**Comment by jywarren** [comment]
Solved in https://github.com/publiclab/PublicLab.Editor/pull/818!!!
