### ISSUE TITLE
Multiple pop-ups at once when tool buttons are clicked.

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/PublicLab.Editor#750]
![Screenshot 2021-10-13 at 12 30 05 AM](https://user-images.githubusercontent.com/49737323/137398410-a6b52aaf-f7fa-4d73-a00d-45e5ea11048d.png)

I clicked on several tool buttons such (e.g table, link etc...) and all corresponding popups occurs. However, they stay on screen until you click again on the icon that triggered the pop-up.

I expect a pop-up to close when I do one of the following:
* click the `esc` button,
* click on the page,
* click on another pop-up (to close previously opened pop-up).

This issue can be replicated on the [publiclab editor](https://publiclab.org/post) by clicking the tool buttons as you see in the image above.

**Comment by RaviAnand111** [comment]
hey @NARUDESIGNS are you working on it, if you are busy, I can work on it ?

**Comment by TildaDares** [comment]
Hi @NARUDESIGNS, can @RaviAnand111 work on this?

**Comment by NARUDESIGNS** [comment]
Sure, @RaviAnand111 can work on it. I'm currently working on completing the conversion of all test files from jasmine tests to jest tests.
cc @TildaDares

**Comment by RaviAnand111** [comment]
Hey guys, I found out that, to make popups to disappear on click on the page or another pop-up is to add 
`$("...").attr('data-trigger', 'focus');`, so I have added it in table and others but I am not able to find module or code for attachments, insert link, insert image where can I find those modules code. ?
@TildaDares @NARUDESIGNS @jywarren 
Thanks

**Comment by TildaDares** [comment]
@RaviAnand111 You should be able to make those changes in this file
https://github.com/publiclab/PublicLab.Editor/blob/1ab7b20561068c5d3f8061f1de14bae38a4314d3/src/adapters/PublicLab.Woofmark.js#L318-L327

**Comment by RaviAnand111** [comment]
Hey @TildaDares , where can I find `.wk-prompt` `.wk-command` classes in html, I can't find it, it is just being called by jquery. and it is somehow working.
@NARUDESIGNS

**Comment by RaviAnand111** [comment]
![image](https://user-images.githubusercontent.com/59113935/148648628-bd6bd17a-9c3a-404e-9d3d-663b2443b981.png)

Hey @TildaDares  @NARUDESIGNS, as in the image, click has been crossed in vs code and on hovering it is saying it has been deprecated so is this function working or not?

**Comment by RaviAnand111** [comment]
https://user-images.githubusercontent.com/59113935/148649041-734f715e-6c73-4e19-89b8-f9f74bee7bb9.mp4


Hi everyone, I wanted to know your views on it ? Am I missing something here ?

**Comment by RaviAnand111** [comment]
why are we using older bootstrap version and functions ?

**Comment by NARUDESIGNS** [comment]
> ![image](https://user-images.githubusercontent.com/59113935/148648628-bd6bd17a-9c3a-404e-9d3d-663b2443b981.png)
> 
> Hey @TildaDares @NARUDESIGNS, as in the image, click has been crossed in vs code and on hovering it is saying it has been deprecated so is this function working or not?

@RaviAnand111 I think it still works, I've seen some other events crossed in vscode as well.

**Comment by NARUDESIGNS** [comment]
I don't know much how popovers work yet but this was the approach I wanted to take: 
I know there is something like `$('.element').popover('hide')` and so I wanted to do a check if the `esc` button is clicked, or if an element that isn't the popped over modal is clicked then based on that, I'd trigger the `$('.element').popover('hide')` method to hide it.
@RaviAnand111

**Comment by RaviAnand111** [comment]
Ok, Thanks, @NARUDESIGNS I will try doing that.

**Comment by NARUDESIGNS** [comment]
I tried something that worked but it will require a little more code. Here's the snippet I tried:

```javascript
 $('.woofmark-command-table').popover({html: true});

+  let popoverIsOpen = false;
  $('.wk-commands .woofmark-command-table').click(function() {
+    popoverIsOpen = !popoverIsOpen;
    $('.ple-table-size').click(function(e) {
      wysiwyg.runCommand(function(chunks, mode) {
        var table = createTable(
            +Number($('.ple-table-popover #tableCols').text()),
            +Number($('.ple-table-popover #tableRows').text())
        );

        if (mode === 'markdown') chunks.before += table;
        else {
          chunks.before += _module.wysiwyg.parseMarkdown(table);
          setTimeout(_module.afterParse, 0); // do this asynchronously so it applies Boostrap table styling
        }

        $('.woofmark-command-table').popover('toggle');
      });
    });

+    $(':not(".woofmark-command-table")').click((e) => {
+      if (popoverIsOpen && !e.target.classList.contains("woofmark-command-table")) {
+        // console.log("popover is opened and should now close");
+        $('.woofmark-command-table').click();
+      }
+    });
  });
```

The lines with the "+" sign are the lines are added. And the file is [PublicLab.RichTextModule.Table.js](https://github.com/publiclab/PublicLab.Editor/blob/main/src/modules/PublicLab.RichTextModule.Table.js) from line 79.
What I did was basically add a `popoverIsOpen` boolean so that when the popover is triggered, this boolean is set to true. 
the part where you see `$(':not(".woofmark-command-table")').click...` is basically saying, if any element is clicked other than the table button (which usually triggers the popover), call the `click()` method on the table button which will then close the popover and set `popoverIsOpen` to false.

This works but with some issues, if you click on any elements in the popover, it will also close the popover since the rule is to close it when any element other than the table button is clicked. This will require more code, but the way I plan to tackle this one is to have all the classes of elements in the popover in an array and do a check against them in the if block.

**Comment by RaviAnand111** [comment]
This is great, and the idea with array is cool too, I was getting confused in this part of how to shut down pop over when something else is clicked. 
@NARUDESIGNS

**Comment by RaviAnand111** [comment]
I have also find a way , with least no of code lines.

**Comment by NARUDESIGNS** [comment]
> I have also find a way , with least no of code lines.

Awesome, please share. @RaviAnand111

**Comment by RaviAnand111** [comment]
How do I share the code like you did ? @NARUDESIGNS

**Comment by NARUDESIGNS** [comment]
````javaScript
// code in here
````

**Comment by RaviAnand111** [comment]
See the last line with + in this code 

```
     $('.woofmark-command-table').attr('data-content', builder);
     $('.woofmark-command-table').attr('data-container', 'body');
     $('.woofmark-command-table').attr('data-placement', 'top');
  + $('.woofmark-command-table').attr('data-trigger', 'focus');

```

By just adding this, button is doing everything we want, execpt one thing, 
popup is disappearing on clicking everything but the popup button, to make that happen I am trying to write code,

**Comment by NARUDESIGNS** [comment]
OK cool. But I have a question, when you click on the popover itself or any of it's child elements like the `-` and `+` buttons, does it disappear?
@RaviAnand111

**Comment by RaviAnand111** [comment]
No, id does not, @NARUDESIGNS

**Comment by NARUDESIGNS** [comment]
OK, cool!

**Comment by RaviAnand111** [comment]
I have a doubt, let me check

**Comment by RaviAnand111** [comment]
actually, it is disappearing on clicking its child elements, sorry about that, I didn't check it earlier.

**Comment by RaviAnand111** [comment]
so, now I'd have to write code for popup button and child elements except add button also.

**Comment by RaviAnand111** [comment]
What do you think ?

**Comment by NARUDESIGNS** [comment]
> actually, it is disappearing on clicking its child elements, sorry about that, I didn't check it earlier.

Oh ok, this was the issue with my own approach as well. How do you intend to tackle this?

**Comment by RaviAnand111** [comment]
I don't know yet, I have solved the problem with the popup button and now it can be used to disappear, now I just have to do the same with child buttons, I will try to do that, and tell you what I got.

**Comment by RaviAnand111** [comment]
hey guys, I am so sorry, I gave my whole day to this problem and I still couldn't solve it, I am getting more and more confused. 
@NARUDESIGNS @TildaDares

**Comment by NARUDESIGNS** [comment]
It's okay @RaviAnand111 we all feel like that sometimes. I'm currently confused with what actions to take for some of my task but we can always communicate to see how we can make progress 💪

**Comment by NARUDESIGNS** [comment]
So for now, you've been able to solve the part where a click on the page or on the table button can hide the popover. 

But the problem is that when you click on elements in the popover, it also hides the popover right?

**Comment by RaviAnand111** [comment]
sure, @NARUDESIGNS , thanks,

**Comment by RaviAnand111** [comment]
yes that is the problem

**Comment by NARUDESIGNS** [comment]
> See the last line with + in this code 
> 
> ```
>      $('.woofmark-command-table').attr('data-content', builder);
>      $('.woofmark-command-table').attr('data-container', 'body');
>      $('.woofmark-command-table').attr('data-placement', 'top');
>   + $('.woofmark-command-table').attr('data-trigger', 'focus');
> 
> ```
> 

Can you please tell me what file you added this line to?

**Comment by NARUDESIGNS** [comment]
I'd also work on my initial solution (though it's more code than yours) to see if I'm able to solve this problem you're having as I also have that problem with my initial solution.

**Comment by RaviAnand111** [comment]
yeah sure, the file is `src/modules/PublicLab.RichTextModule.Table.js`, 
and there is 1 more problem, on adding the code I said, the popover is not disappearing on clicking on the table button so that is also a problem to be solved, 
overall the solution you gave is much better than the code I advised,
so tell me what should we do.

**Comment by NARUDESIGNS** [comment]
Ok, maybe what I can do is to try to fix it, make a PR and we can evaluate the changes together, and based on that, we can solve for other popovers. How about that?

**Comment by RaviAnand111** [comment]
Ok, I am going to make a PR then
