### ISSUE TITLE
Table popover button content not visible on hover.

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/PublicLab.Editor#752]
The buttons `-` `+` `Add` seem to be invisible on hover. I would expect the contents of the buttons to be white on hover since on hover the background colour changes to the default text colour. Also, the text and buttons in the `Table` popup (`-`4`+`x-3`+``Add`) seem to be tightly packed together, a subtle padding will suffice.

Here's an image to describe this:

![Screenshot 2021-10-24 at 04 31 55](https://user-images.githubusercontent.com/49737323/138580549-95019466-6b89-445a-b881-3b0aaee36b16.png)

**Comment by jywarren** [comment]
Hi all - just in case helpful, the HTML for the instance of the editor on plots2 is at:

https://github.com/publiclab/plots2/tree/main/app/views/editor/rich.html.erb

**Comment by RaviAnand111** [comment]
Hi everyone, can I work on this issue, I just got done with the previous issue. @TildaDares @NARUDESIGNS .

**Comment by jywarren** [comment]
@RaviAnand111 if @NARUDESIGNS would like to help you make an issue from this, that would be great!

**Comment by TildaDares** [comment]
Hi @NARUDESIGNS, is this issue still open for @RaviAnand111 to work on?

**Comment by NARUDESIGNS** [comment]
> Hi @NARUDESIGNS, is this issue still open for @RaviAnand111 to work on?

Hi @TildaDares yea that's okay.

**Comment by RaviAnand111** [comment]
Hey @NARUDESIGNS, I just made a video of what I found on my local app, on hovering buttons are white, so there is 1 problem of padding in the buttons and elements that has to be solved and 2nd problem is on hovering the table text is visible that works fine but on clicking that text is again visible and it not goes away on clicking on tables button either you have to click on the page to make it disappear, so that has to be solved as well. If you have any more problems on your mind please share those 
Thanks.

**Comment by NARUDESIGNS** [comment]
* For the problem of padding, that is true.
* For the 2nd problem about hovering and clicking, sorry I don't fully get you. Maybe you can share with me the video you made so that I can see some of the things you explained. Thanks!
@RaviAnand111

**Comment by RaviAnand111** [comment]
Yeah sure, I will work on the padding part first and let you know, then we can talk about the hovering problem. Should I share the video here itself or on Gitter ?
@NARUDESIGNS

**Comment by NARUDESIGNS** [comment]
@RaviAnand111 alright cool, Gitter is fine.

**Comment by RaviAnand111** [comment]
okay, Thanks

**Comment by RaviAnand111** [comment]
Is this much padding fine @NARUDESIGNS 
![image](https://user-images.githubusercontent.com/59113935/147536546-d868239c-aaf8-4e56-8069-89105c189cf7.png)
I have given some padding, but I am thinking of increasing the font-size of variables, but having hard time doing that. 
Do you think the font-size should be increased. ?

**Comment by RaviAnand111** [comment]
@TildaDares , what do you think ?

**Comment by TildaDares** [comment]
@RaviAnand111 Maybe we could reduce the padding a little. There's too much space between the buttons. Something like this could work

<img width="329" alt="Screenshot 2021-12-28 at 19 19 40" src="https://user-images.githubusercontent.com/63427719/147595423-be85b455-ae04-4f61-9cf4-575d04195331.png">

**Comment by TildaDares** [comment]
Also, I think the buttons could use a tooltip to explain what the `-` and `+` buttons do. It's kind of confusing for a first-time user.

What do you think @NARUDESIGNS? It could be an FTO issue.

**Comment by NARUDESIGNS** [comment]
I had typed out my response earlier and hit the comment button just to find out it wasn't sent. I apologise guys.
@RaviAnand111 I am currently working on padding and UI refinement of the PublicLab Editor page as well as other components in the page like popovers and dropdowns. I think for the sake of consistency, we need to define font sizes across elements on the page.

**Comment by NARUDESIGNS** [comment]
> Also, I think the buttons could use a tooltip to explain what the `-` and `+` buttons do. It's kind of confusing for a first-time user.
> 
> What do you think @NARUDESIGNS? It could be an FTO issue.

Yes, I agree. Maybe it should read **decrease row** and **add row** or **decrease column** and **add column**, something like that. We could make it an FTO too. But do you think we can just use the HTML `title` attribute on those buttons rather than make and style a custom tooltip? @TildaDares 
I think the former will be a lot easier than the latter.

**Comment by RaviAnand111** [comment]
Yeah @TildaDares I will decrease the padding a little bit. and about the tooltip should I add it ? as @NARUDESIGNS is working on the font-sizes, what do you guys think ?

**Comment by NARUDESIGNS** [comment]
@RaviAnand111 we are planning to make it a first timer issue, for someone new to publiclab. So instead of solving it, we just show the first time contributor what to add and where to add it, to get them started.

**Comment by RaviAnand111** [comment]
ok, cool, I understand that is perfect. So the padding part is also included in it, right ? So I should try to work on different issue right? 
@NARUDESIGNS

**Comment by NARUDESIGNS** [comment]
You can go ahead and adjust the padding like @TildaDares suggested.
Then you can look for some other issue to work on. 
Well done! @RaviAnand111 🔥🔥🔥

**Comment by RaviAnand111** [comment]
Thanks alot 🎉 🔥

**Comment by RaviAnand111** [comment]
Hey @TildaDares 
is this much padding fine ?
![image](https://user-images.githubusercontent.com/59113935/147642006-fb7cc7db-b857-4a94-af1d-12ce91b70b24.png)

**Comment by TildaDares** [comment]
@RaviAnand111 That’s perfect

**Comment by RaviAnand111** [comment]
Hey @NARUDESIGNS @TildaDares I have created a PR #768 for padding in the button. Can any one you guys review it please. 
ThankYou

**Comment by NARUDESIGNS** [comment]
> Also, I think the buttons could use a tooltip to explain what the `-` and `+` buttons do. It's kind of confusing for a first-time user.
> 
> What do you think @NARUDESIGNS? It could be an FTO issue.

![Screenshot 2022-01-03 at 14 22 31](https://user-images.githubusercontent.com/49737323/147935583-71dcdff3-2ff7-46ce-a8b0-f261a5dea731.png)

This should do the trick. I can create an FTO right away for these changes but I need your opinions/suggestions first @TildaDares

**Comment by TildaDares** [comment]
@NARUDESIGNS One of the buttons on the toolbar doesn't have a tooltip. That could also be an FTO

<img width="613" alt="Screenshot 2022-01-04 at 17 19 41" src="https://user-images.githubusercontent.com/63427719/148090062-9f060295-40e3-4cdc-b413-e8dfd0ce6bd1.png">

**Comment by NARUDESIGNS** [comment]
> @NARUDESIGNS One of the buttons on the toolbar doesn't have a tooltip. That could also be an FTO

HI @TildaDares I've opened an FTO for this here - https://github.com/publiclab/PublicLab.Editor/issues/779
Thank you for pointing it out, here's a screenshot of the final result below:

![Screenshot 2022-01-08 at 13 15 00](https://user-images.githubusercontent.com/49737323/148643795-447548a3-7c22-4f09-afc4-0c1f34acaa2f.png)
