### ISSUE TITLE
Buttons has no background which makes it possible to see text behind it.

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/PublicLab.Editor#753]
When the page is scrolled to a particular threshold, the tool buttons sticks to the page, allowing other contents to scroll under them. However, the tag, table, horizontal line, center and youtube buttons all have no backgrounds which make it possible to see the text which they overlap.
I expect those buttons to have a background and maybe match other button styles like the bold, italics, blockquotes etc...

Here's what it looks like presently

![Screenshot 2021-10-24 at 06 18 34](https://user-images.githubusercontent.com/49737323/138582128-ba688423-6eff-4b9e-a9be-5bf79c27ad35.png)

**Comment by NARUDESIGNS** [comment]
Hi, @TildaDares trust you're good. I just checked https://publiclab.org/post again (which isn't my local environment), populated it with large lorem ipsum texts and this issue still exist. 
![Screenshot 2021-10-31 at 21 03 15](https://user-images.githubusercontent.com/49737323/139599585-cdb8431c-34ff-489a-b0f2-2693622248e3.png)
Please check and confirm so I can reopen the issue and work on it.

**Comment by TildaDares** [comment]
Hi @NARUDESIGNS, I think the transparent background is because of the `btn-outline-secondary` class.

**Comment by NARUDESIGNS** [comment]
Yes, you're right, it has background property set to transparent in css. Should you place this as an FTO or I should go ahead and remove the background class property?
![Screenshot 2021-11-01 at 11 22 52](https://user-images.githubusercontent.com/49737323/139657521-b7448891-fb1b-48b3-b9dd-5cce787636b5.png)

**Comment by TildaDares** [comment]
> Should you place this as an FTO issue or I should go ahead and fix it by removing the background class property?

Either one works

**Comment by RaviAnand111** [comment]
If this issue is still open can I do this small task, it is my first open-source contribution.

**Comment by TildaDares** [comment]
Hi @NARUDESIGNS, has this issue been resolved?

**Comment by NARUDESIGNS** [comment]
No it hasn't, @RaviAnand111 can take on it since it's his first time contributing.
@TildaDares

**Comment by TildaDares** [comment]
Hi @RaviAnand111, I've assigned this issue to you. If you need any help, feel free to ask.

**Comment by RaviAnand111** [comment]
ok, thankyou

**Comment by RaviAnand111** [comment]
Hi @TildaDares I have forked and cloned the project, I did npm install then installed grunt and open the example/index.html file and I am able to change css in the dev tools section as well. 
Can you please tell me what should I do now and in which file can I make changes in bootstrap or css.

**Comment by TildaDares** [comment]
@RaviAnand111 You need to change `btn-outline-secondary` to `btn-light` in this file
https://github.com/publiclab/PublicLab.Editor/blob/f8e1edb6ff992a03aa593feae53783f2b9867bd2/src/adapters/PublicLab.Woofmark.js#L335

**Comment by RaviAnand111** [comment]
I have changed the btn-outline-secondary to btn-light, now what should I do. 
git add . , git commit -m "btn-light added for transparent btn", then git push origin main, 
then I have to create a PR, 
is that all I have to do now ?

**Comment by TildaDares** [comment]
@RaviAnand111 You have to run `grunt build` before you create a PR.

**Comment by RaviAnand111** [comment]
ok, will do

**Comment by RaviAnand111** [comment]
I have created a PR after running `grunt build`, 
PR #765
