### ISSUE TITLE
Subtract button in table popover displays negative value when decreased below 0

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/PublicLab.Editor#755]
The `-` button for table rows and that of columns in the table popup when clicked reduces the number of expected rows or columns, however, when the number is decreased below 0, we get a negative number. I expect 1 to be the minimum number of selectable rows and the same for columns.
Please see Image below:
![Screenshot 2021-11-04 at 23 28 59](https://user-images.githubusercontent.com/49737323/140429323-3ffcf6b5-1702-4b0b-870d-7c670a1926f1.png)

**Comment by NARUDESIGNS** [comment]
Hi @TildaDares good day, trust you're good.
Please, if I choose to work on this, what file do I need to look at and also do I need to write any test afterwards (I don't know so much about writing tests yet)?

**Comment by TildaDares** [comment]
Hi @NARUDESIGNS, you can find it in https://github.com/publiclab/PublicLab.Editor/blob/main/src/modules/PublicLab.RichTextModule.Table.js#L60-L71

I'm not sure about the test part but you can check if there is a test already written for that feature and update it.

**Comment by NARUDESIGNS** [comment]
ok @TildaDares thank you, I will check it out.

**Comment by NARUDESIGNS** [comment]
@TildaDares I've been able to resolve this issue but didn't find any test for the button. Should I maybe push my changes for review and then you can let me know if it requires further actions?
cc @jywarren

**Comment by TildaDares** [comment]
@NARUDESIGNS Yes you can push your changes

**Comment by NARUDESIGNS** [comment]
Hi @TildaDares I think we can close this now since the PR for it has been merged.

**Comment by jywarren** [comment]
Agree! Paul, do you want to see if you can close it yourself? I added
permissions!

**Comment by NARUDESIGNS** [comment]
@jywarren ok thank you.
