### ISSUE TITLE
Column subtract button in table popover has no style

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/PublicLab.Editor#756]
The `-` button for columns has no style, making it difficult to tell whether or not it is a button.
It should match the style of the other buttons.
See image for you reference: 
![Screenshot 2021-11-04 at 22 48 05](https://user-images.githubusercontent.com/49737323/140429736-212e2a7a-33ef-40bc-ae73-8a05c1ab5dc3.png)

**Comment by NARUDESIGNS** [comment]
Hi @jywarren, trust you're good?
I remember you mentioned where the HTML file for the Public Lab Editor is but I can't seem to remember, can you please remind me? 
I found the cause of this issue, it's in the HTML code. The class name was misspelt.
cc @TildaDares

**Comment by TildaDares** [comment]
Hi @NARUDESIGNS, @jywarren mentioned it here https://github.com/publiclab/PublicLab.Editor/issues/752#issuecomment-962476362

**Comment by NARUDESIGNS** [comment]
Thank you so much @TildaDares

**Comment by jywarren** [comment]
Hi! Great find on that typo. The line of code is here -- it's a "submodule" of the rich text module!

https://github.com/publiclab/PublicLab.Editor/blob/b38a9aee262c5d6242cb18d39aa7707e417bde06/src/modules/PublicLab.RichTextModule.Table.js#L53

**Comment by NARUDESIGNS** [comment]
@jywarren Yea thanks, I think my PR captured that as well. Please have a look at the changes in the code here 
https://github.com/NARUDESIGNS/PublicLab.Editor/commit/d7e2a0aa585a440452bc0a9ec89f5f040e6b5aa

![Screenshot 2021-11-14 at 20 27 35](https://user-images.githubusercontent.com/49737323/141695537-44fed453-5c07-43a0-bec1-fbadb3fa8f8c.png)

**Comment by jywarren** [comment]
Ah, actually @NARUDESIGNS would you mind opening a PR for your changes? It's easier to keep all our reviews in one place then. Thank you!

**Comment by NARUDESIGNS** [comment]
@jywarren I opened a PR for it here - https://github.com/publiclab/PublicLab.Editor/pull/758
@TildaDares was kind to review and asked for some changes which I've also completed. I'm waiting for my PRs to be merged. This is one of them, there's another (this one #757 which fixes issue #755)

**Comment by jywarren** [comment]
Was this now resolved? Just checking - we can close it if so!

**Comment by NARUDESIGNS** [comment]
> Was this now resolved? Just checking - we can close it if so!

Yes, you just merged it #758
