### ISSUE TITLE
Rename title header in title section from "1" to "Add title", centre elements and give proper padding to its input field

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/PublicLab.Editor#762]

**Comment by noobyogi0010** [comment]
Hi, @NARUDESIGNS 
If this issue is not resolved yet, can I work upon it??

**Comment by NARUDESIGNS** [comment]
Hello, thank you for your interest in that issu. However, there's been a change in direction and the issue has to be closed.
But I believe you can find some other issues to work on.

Cheers!
