### ISSUE TITLE
Minor fix in the tooltip

### ISSUE THREAD

**Issue by avi-jain** [publiclab/PublicLab.Editor#79]
Hello, while trying to get a hang of the codebase I noticed a relatively insignificant issue that the tooltip-arrow wasn't positioned properly in the example page. Can get rid of the arrow simply by adding `.tooltip.bottom .tooltip-arrow {
display:none;}` to the css.

**Comment by jywarren** [comment]
Oh wow, thank you! Do you think you could open up a pull request?
