### ISSUE TITLE
dropdown button in custom insert popover has no style

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/PublicLab.Editor#798]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [PublicLab.CustomInsert.Template.js](https://github.com/publiclab/PublicLab.Editor/blob/main/src/modules/PublicLab.CustomInsert.Template.js#:~:text=builder%20%2B%3D%20'%3Cbutton%20class%3D%22btn%20btn-outline-secondarydropdown-toggle%20dropdownmenu2%22%20type%3D%22button%22%20data-toggle%3D%22dropdown%22%20aria-haspopup%3D%22true%22%20aria-expanded%3D%22true%22%20style%3D%22min-width%3A%20150px%3B%22%3E'%3B) in the `PublicLab.Editor` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- builder += '<button class="btn btn-outline-secondarydropdown-toggle dropdownMenu2" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="min-width: 150px;">';
+ builder += '<button class="btn btn-outline-secondary dropdown-toggle dropdownMenu2" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="min-width: 150px;">';

```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by NARUDESIGNS** [comment]
### This button currently looks like this:

<img width="394" alt="Screenshot 2022-01-21 at 10 36 29 AM" src="https://user-images.githubusercontent.com/49737323/150504156-4becae71-1fa5-42cf-8615-d0e53d6d4c2a.png">

### After making changes, it should look like this:

<img width="379" alt="Screenshot 2022-01-21 at 10 42 18 AM" src="https://user-images.githubusercontent.com/49737323/150504254-31db9f08-01c7-4403-a1ca-7b1302f50746.png">


cc @TildaDares

**Comment by TildaDares** [comment]
This looks good @NARUDESIGNS

**Comment by Innominata88** [comment]
Has anyone claimed this issue yet? I've been afraid to take the plunge and contribute to an open source repo and this seems like a good opportunity to gain some confidence since you all seem so friendly and helpful. :)

**Comment by bittu426** [comment]
Hello, I'm Chaitanya and I've been asked to contribute to an open-source project for my Software Development course. I'm interested to work on this issue and it'd be great if I could be assigned to this. Thank you so much.

**Comment by TildaDares** [comment]
Hi @bittu426, there’s an open issue for you to work on in https://github.com/publiclab/spectral-workbench/issues/858 if you’re interested.

**Comment by bittu426** [comment]
Yes. I'm interested. Can I be assigned for that issue?

**Comment by TildaDares** [comment]
@bittu426 Leave a comment in the issue and if no one has claimed it you can start working on it.

**Comment by singla-nitin** [comment]
Hey , has someone been assigned to this issue or can work on it and pls someone guide as to how to do it and move forward as I am totally new to open source and github. 
a reply will be appreciated .
