### ISSUE TITLE
Refine UI of the main-image section in the PublicLab Editor

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/PublicLab.Editor#842]
Hi, @TildaDares 
I'm trying to refine the UI of the main-image section for mobile view.
Here's what it currently looks like:

<img width="381" alt="Screenshot 2022-02-16 at 11 00 40 AM" src="https://user-images.githubusercontent.com/49737323/154699450-4c4d60a4-4e24-4c8b-89e4-c8fbec6cd79f.png">\

Here's what I'm trying to achieve:

<img width="347" alt="Screenshot 2022-02-16 at 11 15 41 AM" src="https://user-images.githubusercontent.com/49737323/154699459-47e64f6f-57c0-44a6-b090-e2a0a8a3a187.png">

**Comment by TildaDares** [comment]
To add a new class, you need to add the class in https://github.com/publiclab/plots2/blob/main/app/views/editor/rich.html.erb
and if you also want that same change also add it to the HTML file in https://github.com/publiclab/PublicLab.Editor/blob/main/examples/index.html. The CSS can be added to the PublicLab.Editor CSS file.

**Comment by NARUDESIGNS** [comment]
Great, this brings me to my first idea with using the `examples/index.html` file in the PublicLab.Editor project which we discussed on Gitter(or Matrix).
If I add the classes to the `examples/index.html` file when it gets merged, will the changes impact the editor when it gets merged to plots2?

**Comment by TildaDares** [comment]
No it won’t. You have to also add that class in the plots2 html file.

> If I add the classes to the examples/index.html file when it gets merged, will the changes impact the editor when it gets merged to plots2?

**Comment by NARUDESIGNS** [comment]
Hmm, this here was my confusion.   
But ok, I'd give it a try. Thank you @TildaDares

**Comment by NARUDESIGNS** [comment]
Or what if I add the class using javascript, does that pose any problem in your opinion? @TildaDares 
I worry that changing the class names in plots2 and then in the editor might not be the best approach.

**Comment by TildaDares** [comment]
No it doesn’t

**Comment by NARUDESIGNS** [comment]
I think I just got it. Let me make a PR so we can discuss my approach there.
Thank you very much @TildaDares I'd send you the PR soonest
