### ISSUE TITLE
Weekly Community Check-In #143 - New Technologies

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/PublicLab.Editor#863]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## New Technologies 
This week lets  share something new(library/language/e.t.c) we've learnt/ are learning and tell us what has fascinated you  about it. I have been looking at Elixir for a while now.  I recently started looking at  Phoenix(_an Elixir  web framework_) and the [LiveView Module](https://github.com/phoenixframework/phoenix_live_view) in particular has really impressed me.

### :star2: :star2:  Thank you note to contributors :star2: :star2: 
Thanks to the contributors of the past few weeks :-
 [@TildaDares](https://github.com/TildaDares), [@rajvidg](https://github.com/rajvidg), [@jywarren](https://github.com/jywarren), [@thisiskaransgit](https://github.com/thisiskaransgit), [@fedechaves](https://github.com/fedechaves), [@illyShelly](https://github.com/illyShelly), [@ronran1](https://github.com/ronran1), [@simransia](https://github.com/simransia), [@Forchapeatl](https://github.com/Forchapeatl), [@mittal-parth](https://github.com/mittal-parth), [@PlusUltra404](https://github.com/PlusUltra404)

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by NARUDESIGNS** [comment]
For me, I learned a great deal or Vuejs, options API and Composition API, and Vue Router.
I also learned to work with git on Microsoft azure devOps tool.

✌️😊

**Comment by SHIVANGISINGH1** [comment]
I am learning react for now and for the past 2 weeks I am doing Redux in react. I also learned crud in firebase last week. 😊😊

**Comment by PeculiarE** [comment]
Thanks for sharing ❤️  @cesswairimu.

These past few weeks, I've been focusing on trying to deepen my understanding and knowledge of the Ruby on Rails framework as it forms a huge part of my Outreachy project.
 
In my spare time, I started exploring the NestJs framework, heard and read a lot of wonderful things about it and its edge over other Javascript frameworks. And so far, it is living up to expectations 😀

**Comment by stephaniequintana** [comment]
Hi, everyone! 👋 😄 

I'm so excited to be back here and starting this Outreachy internship!!! ❤️ 🚀 🥳 

In the interim of the proposal due date and intern announcement, I spent a lot of time focused on personal projects and reconnecting with extended family, a blessing I wish I could take advantage of more often. I (very-nearly-almost & FINALLY!!) completed my personal website and resume and focused a lot on answering questions in a few of the discord groups I'm involved with. It's amazing how much explaining something to others helps solidify my own knowledge. 🤓 

Last week, I combed through the [Welcome packet](https://docs.google.com/document/d/1NwWrIhumVxVa0i__ZRMY9upLh6LmzNrG-0PtnZo4LZE/edit#) that Jeff sent to us newbies - I found [A Guide to Modualar Design Thinking](https://ponyfoo.com/articles/modular-design-thinking), refernced [here](https://github.com/publiclab/plots2/issues/5794#issue-448487637), particulary interesting. It was an excellent recap and lent some very solid ground on our aim here. I was also able to wrap up a few of my learning initiatives to clear the way for my focus on Instagram and [Forchapeatl](https://github.com/Forchapeatl) and I connected and set up a time to begin collaborating.

This week I will be hammering out my planning issues/milestones and learning a bit more about the project as a whole. 

Again, I am so very excited to be back here and very much looking forward to taking this journey with you all! ❤️ 🚀 🥳 🎈

**Comment by jywarren** [comment]
Hi all! So glad to see you all, and thanks Cess for a great topic. 

I've been kind of resisting learning React, to be honest -- although it's quite ubiquitous, and we use React in some of our systems (plots2, on a test basis), it's just a very different paradigm and I keep thinking... is it really necessary? As someone who started coding before NPM existed, before JavaScript was standardized, I sometimes feel like I have to re-learn every few years. But I'll probably come around sooner or later!

One new tech I have learned recently is a bit of GitHub Actions. Writing scripts that can interact with a pull request is... kind of fun! 😵‍💫 😂  Learning how they're triggered, what they have access to, how we can make community support systems and infrastructure with them... well, it's pretty cool. 

Thanks, all! @stephaniequintana @PeculiarE let me know if you need input on what your next step should be, or if you're feeling overwhelmed, or if you just want to connect! We'll be doing a larger call once the GSoC program begins but we can also do something sooner.

**Comment by cesswairimu** [comment]
Would anyone like to open this week's check-in?

**Comment by NARUDESIGNS** [comment]
I'd love to
When can I do so?
@cesswairimu

**Comment by cesswairimu** [comment]
thats awesome @NARUDESIGNS, anytime today is  fine. Thanks

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/PublicLab.Editor/issues/869. Thanks all
