### ISSUE TITLE
Weekly Community Check-in #144 -  IT'S OKAY

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/PublicLab.Editor#869]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## IT'S OKAY
Hi guys, I wanted to share a bit of my journey with you and some of the issues I faced (and still face) as a software engineer which you have probably faced as well or are currently facing. It's okay, you'd pull through!

I was an Outreachy intern with PublicLab in the last cohort and prior to this time, I had applied about 4 times before I finally got selected. While I understand that it can be very competitive, it can also be very heartbreaking to give your best every time and look like you failed. But I usually said to myself "It's Okay, you can try again!" 
Finally, I got selected by PublicLab and it was a huge part of my career because I had not worked on a large codebase with a remote team like this before. To add to it, I had to work with technologies I've not used before and it was worrisome. At a point, I reached out to @jywarren who was my mentor at the time and told him how I was worried because I wasn't good at using the technology and he said "That's Okay, ..." Long story short, I was able to pull through by accepting that it's okay to feel the way I felt and that helped me focus on getting the work done rather than on my lack of ability.

After Outreachy, I began job hunting and applied to over 100+ companies, all with rejections and very few interviews. Again I started to feel like my resume was bad, I wasn't good enough and no one will consider me for the position I wanted. I then read a post on Twitter seeing how other people have applied to even more companies than I did. So I accepted it was okay to get rejected but I will keep on applying and with this mindset, I didn't feel bad when I get the usual "Unfortunately, we were unable to move forward with your application...", in fact, I started responding to the recruiters, saying "Thank you for your response!"

I finally got a job last 2 weeks and even now there are some issues that bother me but I accept it's okay to feel the way I feel and this helps me be calm and focus on what I need to do.

So it's okay to be confused, it's okay to be worried about not having a particular skill, it's okay to ask questions and seek help, it's okay to be scared and worried in these times with what's going on around us, it's okay to cry and sob. IT's OKAY!

We are humans, after all, so do what you can and be OKAY ❤️

### :star2: :star2:  Thank you note to contributors :star2: :star2: 
Thanks to the contributors of the past few weeks :-
 [@TildaDares](https://github.com/TildaDares), [@rajvidg](https://github.com/rajvidg), [@jywarren](https://github.com/jywarren), [@thisiskaransgit](https://github.com/thisiskaransgit), [@fedechaves](https://github.com/fedechaves), [@illyShelly](https://github.com/illyShelly), [@ronran1](https://github.com/ronran1), [@simransia](https://github.com/simransia), [@Forchapeatl](https://github.com/Forchapeatl), [@mittal-parth](https://github.com/mittal-parth), [@PlusUltra404](https://github.com/PlusUltra404)

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by jywarren** [comment]
Thank you Paul for such a great message. I have to remember this myself especially when I get overwhelmed by a lot of complex issues and just can't get something to work! I'm glad to be part of a community where we look out for each other and know that it's OKAY!!! 🌠

**Comment by stephaniequintana** [comment]
Wow @NARUDESIGNS, CONGRATULATIONS on your new job!!! ⚡ 🌟 🥳 ❤️ 🎉 

I am especially grateful for you sharing your story - rejection can be do disheartening, but your perseverance is truly inspiring. This is also my first time working with a large codebase and technologies I'm unfamiliar with. At times it can be overwhelming and I wonder if I bit off more than I can chew! You're so right, though, everyone feels discouraged at times and focusing on the task at hand is the most effective way to move forward. It is all a part of our learning journey!

**Comment by on2onyekachi** [comment]
Thanks so much @NARUDESIGNS Congrats on your new Job 🎉.  

At the very least, the easiest way to move on is to find peace in the present as it will likely light the path to a new beginning.

**Comment by cesswairimu** [comment]
would anyone like to open next week's check-in?

**Comment by RaviAnand111** [comment]
Thank You @NARUDESIGNS for sharing your journey, Thank You for inspiring us. I know its been hard cause I am in the phase you were before. You have inspired me alot and I am not going to stop I am going to persevere. I am going to push through learn and grab new better opportunities. 

Thank You everyone in the Public Lab Community

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/11200. thanks all
